INSERT INTO Customer VALUES(0, 'Erick', 'Allison', 'ErickAllison@palock.com', '82 Elizabeth Street Chelmsford, MA 01824');
INSERT INTO Customer VALUES(1, 'Gerard', 'Nelson', 'GerardNelson@iniclu.com', '24 8th Avenue Randallstown, MD 21133');
INSERT INTO Customer VALUES(2, 'Milton', 'Martinez', 'MiltonMartinez@poleal.com', '807 East Street Jamaica, NY 11432');
INSERT INTO Customer VALUES(3, 'Florence', 'Sutton', 'FlorenceSutton@neupps.com', '393 Virginia Street Lutherville Timonium, MD 21093');
INSERT INTO Customer VALUES(4, 'Kevin', 'Palmer', 'KevinPalmer@mounox.com', '50 Pheasant Run Cantonment, FL 32533');
INSERT INTO Customer VALUES(5, 'Patti', 'Ramsey', 'PattiRamsey@hoeign.com', '711 Colonial Drive Oxnard, CA 93035');
INSERT INTO Customer VALUES(6, 'Faye', 'Davidson', 'FayeDavidson@sirabo.com', '936 Cherry Lane West Orange, NJ 07052');
INSERT INTO Customer VALUES(7, 'Clint', 'Cook', 'ClintCook@okialm.com', '470 Valley Drive Madison, AL 35758');
INSERT INTO Customer VALUES(8, 'Margarita', 'Harvey', 'MargaritaHarvey@kngeth.com', '322 Walnut Street Northville, MI 48167');
INSERT INTO Customer VALUES(9, 'Madeline', 'Austin', 'MadelineAustin@exesic.com', '321 Linden Street Bountiful, UT 84010');
INSERT INTO Customer VALUES(10, 'Alexander', 'Sandoval', 'AlexanderSandoval@birrah.com', '786 Jefferson Court Fond Du Lac, WI 54935');
INSERT INTO Customer VALUES(11, 'Barbara', 'Larson', 'BarbaraLarson@huarry.com', '646 Devon Road Hamburg, NY 14075');
INSERT INTO Customer VALUES(12, 'Rodney', 'Black', 'RodneyBlack@ougarl.com', '679 Poplar Street Marlborough, MA 01752');
INSERT INTO Customer VALUES(13, 'Lynette', 'Wallace', 'LynetteWallace@tospam.com', '755 Evergreen Drive Miami Gardens, FL 33056');
INSERT INTO Customer VALUES(14, 'Kyle', 'Daniel', 'KyleDaniel@rageof.com', '118 Summer Street Port Charlotte, FL 33952');
INSERT INTO Customer VALUES(15, 'Bessie', 'Lawson', 'BessieLawson@fenafe.com', '324 Aspen Drive Woodstock, GA 30188');
INSERT INTO Customer VALUES(16, 'Robyn', 'Morales', 'RobynMorales@gnesul.com', '588 Main Street Basking Ridge, NJ 07920');
INSERT INTO Customer VALUES(17, 'Kenneth', 'Hopkins', 'KennethHopkins@voilep.com', '219 Route 17 Ann Arbor, MI 48103');
INSERT INTO Customer VALUES(18, 'Clifton', 'Watts', 'CliftonWatts@zitrix.com', '894 Parker Street Parkersburg, WV 26101');
INSERT INTO Customer VALUES(19, 'Greg', 'Owen', 'GregOwen@slobba.com', '70 Woodland Drive Knoxville, TN 37918');
INSERT INTO Customer VALUES(20, 'Lorraine', 'Love', 'LorraineLove@ferbra.com', '580 Penn Street Portage, IN 46368');
INSERT INTO Customer VALUES(21, 'Nancy', 'Schultz', 'NancySchultz@gielab.com', '134 Queen Street Wyoming, MI 49509');
INSERT INTO Customer VALUES(22, 'Kelly', 'Cox', 'KellyCox@aineth.com', '566 Route 32 Woodhaven, NY 11421');
INSERT INTO Customer VALUES(23, 'Pedro', 'Banks', 'PedroBanks@welema.com', '719 3rd Street West Shelbyville, TN 37160');
INSERT INTO Customer VALUES(24, 'Lula', 'Hogan', 'LulaHogan@sumpsy.com', '731 Garfield AvenueCary, NC 27511');
INSERT INTO Customer VALUES(25, 'Jacquelyn', 'Myers', 'JacquelynMyers@lecalc.com', '642 Church StreetMcminnville, TN 37110');
INSERT INTO Customer VALUES(26, 'Stella', 'Dean', 'StellaDean@reazed.com', '864 5th Street WestTaylor, MI 48180');
INSERT INTO Customer VALUES(27, 'Angel', 'Ortega', 'AngelOrtega@pentet.com', '707 Park StreetMount Holly, NJ 08060');
INSERT INTO Customer VALUES(28, 'Danny', 'Rivera', 'DannyRivera@affort.com', '631 Washington AvenueSaratoga Springs, NY 12866');
INSERT INTO Customer VALUES(29, 'Oliver', 'Adams', 'OliverAdams@snueas.com', '938 South StreetHicksville, NY 11801');
INSERT INTO Customer VALUES(30, 'Gretchen', 'Bryant', 'GretchenBryant@botcon.com', '538 4th Street WestChardon, OH 44024');
INSERT INTO Customer VALUES(31, 'Melanie', 'Cohen', 'MelanieCohen@gactry.com', '472 Route 10Maspeth, NY 11378');
INSERT INTO Customer VALUES(32, 'Jane', 'Bowen', 'JaneBowen@wildor.com', '324 Cleveland Street Woodstock, GA 30188');
INSERT INTO Customer VALUES(33, 'Mark', 'Brown', 'MarkBrown@sveldy.com', '901 Oak Lane Wyandotte, MI 48192');
INSERT INTO Customer VALUES(34, 'Kendra', 'Norton', 'KendraNorton@ahason.com', '821 5th Street Front Royal, VA 22630');
INSERT INTO Customer VALUES(35, 'Dave', 'Lindsey', 'DaveLindsey@oprepy.com', '994 Locust Lane Sylvania, OH 43560');
INSERT INTO Customer VALUES(36, 'Kristy', 'Massey', 'KristyMassey@taluor.com', '225 3rd Street Galloway, OH 43119');
INSERT INTO Customer VALUES(37, 'Claude', 'Mullins', 'ClaudeMullins@khaloc.com', '782 East Street Westminster, MD 21157');
INSERT INTO Customer VALUES(38, 'Jody', 'Morrison', 'JodyMorrison@enolot.com', '730 6th Street Ames, IA 50010');
INSERT INTO Customer VALUES(39, 'Ivan', 'Gregory', 'IvanGregory@aniute.com', '697 Warren Street Grove City, OH 43123');
INSERT INTO Customer VALUES(40, 'Cody', 'Barton', 'CodyBarton@titemy.com', '704 1st Avenue Dorchester Center, MA 02124');
INSERT INTO Customer VALUES(41, 'Franklin', 'Pope', 'FranklinPope@foenez.com', '400 Route 1 New Philadelphia, OH 44663');
INSERT INTO Customer VALUES(42, 'Ralph', 'Reynolds', 'RalphReynolds@euneal.com', '7 Lilac Lane Calhoun, GA 30701');
INSERT INTO Customer VALUES(43, 'Alberto', 'Hardy', 'AlbertoHardy@bedgit.com', '149 College Avenue Cookeville, TN 38501');
INSERT INTO Customer VALUES(44, 'Tommy', 'Murphy', 'TommyMurphy@goolla.com', '940 Devon Road Shakopee, MN 55379');
INSERT INTO Customer VALUES(45, 'Kristine', 'Ellis', 'KristineEllis@icaroe.com', '610 Fairview Avenue Glen Cove, NY 11542');
INSERT INTO Customer VALUES(46, 'Victor', 'Potter', 'VictorPotter@edassa.com', '98 Summer Street Clayton, NC 27520');
INSERT INTO Customer VALUES(47, 'Rickey', 'Fletcher', 'RickeyFletcher@ethyad.com', '229 Wood Street New Bedford, MA 02740');
INSERT INTO Customer VALUES(48, 'Veronica', 'Park', 'VeronicaPark@webome.com', '610 6th Street North Muskogee, OK 74403');
INSERT INTO Customer VALUES(49, 'Cristina', 'Howell', 'CristinaHowell@uncemo.com', '571 Park Place Carmel, NY 10512');
INSERT INTO Customer VALUES(50, 'Lloyd', 'Medina', 'LloydMedina@henisc.com', '406 Cardinal Drive Montclair, NJ 07042');
INSERT INTO Customer VALUES(51, 'Geraldine', 'Stanley', 'GeraldineStanley@xianap.com', '323 Cobblestone Court Lafayette, IN 47905');
INSERT INTO Customer VALUES(52, 'Diane', 'Perry', 'DianePerry@gulaur.com', '162 Essex Court Monroe Township, NJ 08831');
INSERT INTO Customer VALUES(53, 'Danielle', 'Underwood', 'DanielleUnderwood@tsidge.com', '791 Adams Street Farmingdale, NY 11735');
INSERT INTO Customer VALUES(54, 'Hilda', 'Butler', 'HildaButler@etivic.com', '232 Dogwood Lane Dayton, OH 45420');
INSERT INTO Customer VALUES(55, 'Rosalie', 'Williamson', 'RosalieWilliamson@geapan.com', '325 12th StreetS heboygan, WI 53081');
INSERT INTO Customer VALUES(56, 'Wilma', 'Burton', 'WilmaBurton@sidura.com', '591 State Street EastMoorhead, MN 56560');
INSERT INTO Customer VALUES(57, 'Abel', 'Barnes', 'AbelBarnes@jaireo.com', '126 Ashley Court Lake Charles, LA 70605');
INSERT INTO Customer VALUES(58, 'Marlon', 'Hawkins', 'MarlonHawkins@futiff.com', '324 Ann Street Elkhart, IN 46514');
INSERT INTO Customer VALUES(59, 'Nelson', 'Norris', 'NelsonNorris@fagera.com', '766 Aspen Drive Wilmette, IL 60091');
INSERT INTO Customer VALUES(60, 'Brandy', 'Patterson', 'BrandyPatterson@nisade.com', '448 Meadow Lane Rowlett, TX 75088');
INSERT INTO Customer VALUES(61, 'Marguerite', 'Singleton', 'MargueriteSingleton@tursiz.com', '267 Andover Court Dothan, AL 36301');
INSERT INTO Customer VALUES(62, 'Darrell', 'Simpson', 'DarrellSimpson@fiturs.com', '652 Hanover Court Hamilton, OH 45011');
INSERT INTO Customer VALUES(63, 'Guillermo', 'May', 'GuillermoMay@juitra.com', '318 William Street Sacramento, CA 95820');
INSERT INTO Customer VALUES(64, 'Dexter', 'Todd', 'DexterTodd@vivect.com', '539 Lake Street Washington, PA 15301');
INSERT INTO Customer VALUES(65, 'Leon', 'Wade', 'LeonWade@pennus.com', '724 York Street New Berlin, WI 53151');
INSERT INTO Customer VALUES(66, 'Malcolm', 'Hammond', 'MalcolmHammond@aresse.com', '488 Hamilton Street Douglasville, GA 30134');
INSERT INTO Customer VALUES(67, 'Alexis', 'Walker', 'AlexisWalker@blaikh.com', '701 Virginia Avenue Calumet City, IL 60409');
INSERT INTO Customer VALUES(68, 'Guy', 'Reeves', 'GuyReeves@mentue.com', '245 Brown Street Pikesville, MD 21208');
INSERT INTO Customer VALUES(69, 'Edwin', 'Jackson', 'EdwinJackson@haibit.com', '791 Depot Street Hobart, IN 46342');
INSERT INTO Customer VALUES(70, 'Bonnie', 'Aguilar', 'BonnieAguilar@cuvene.com', '318 Railroad Street Arvada, CO 80003');
INSERT INTO Customer VALUES(71, 'Allan', 'Holmes', 'AllanHolmes@fuscro.com', '671 Chestnut Street Niceville, FL 32578');
INSERT INTO Customer VALUES(72, 'Julia', 'Casey', 'JuliaCasey@bodare.com', '886 Franklin Avenue Parkersburg, WV 26101');
INSERT INTO Customer VALUES(73, 'Javier', 'Lane', 'JavierLane@arilop.com', '832 Brandywine Drive Venice, FL 34293');
INSERT INTO Customer VALUES(74, 'Ernesto', 'Hall', 'ErnestoHall@ediltz.com', '139 Main Street West Lawndale, CA 90260');
INSERT INTO Customer VALUES(75, 'Rosa', 'Reyes', 'RosaReyes@loneky.com', '977 East Avenue Reston, VA 20191');
INSERT INTO Customer VALUES(76, 'Lonnie', 'West', 'LonnieWest@cussis.com', '323 4th Street South Roy, UT 84067');
INSERT INTO Customer VALUES(77, 'Francis', 'Young', 'FrancisYoung@tholum.com', '68 East Street Albany, NY 12203');
INSERT INTO Customer VALUES(78, 'Willis', 'Rowe', 'WillisRowe@ureeco.com', '838 Route 32 Milwaukee, WI 53204');
INSERT INTO Customer VALUES(79, 'Robert', 'Knight', 'RobertKnight@sersey.com', '91 Oxford Court Kernersville, NC 27284');
INSERT INTO Customer VALUES(80, 'Dale', 'Ryan', 'DaleRyan@netasy.com', '913 West Street Niles, MI 49120');
INSERT INTO Customer VALUES(81, 'Mandy', 'Townsend', 'MandyTownsend@omnima.com', '94 Division Street Long Branch, NJ 07740');
INSERT INTO Customer VALUES(82, 'Lucia', 'Kennedy', 'LuciaKennedy@oxurer.com', '607 Wood Street Tonawanda, NY 14150');
INSERT INTO Customer VALUES(83, 'Clarence', 'Doyle', 'ClarenceDoyle@golere.com', '989 Cherry Lane Round Lake, IL 60073');
INSERT INTO Customer VALUES(84, 'Melinda', 'Hudson', 'MelindaHudson@elotad.com', '422 Cemetery Road Windermere, FL 34786');
INSERT INTO Customer VALUES(85, 'Micheal', 'Powers', 'MichealPowers@ankeld.com', '537 Willow Avenue Downingtown, PA 19335');
INSERT INTO Customer VALUES(86, 'Nathaniel', 'Berry', 'NathanielBerry@goblex.com', '212 Valley View Drive Rock Hill, SC 29730');
INSERT INTO Customer VALUES(87, 'Steven', 'Miles', 'StevenMiles@gimman.com', '419 2nd Avenue Bakersfield, CA 93306');
INSERT INTO Customer VALUES(88, 'Shelly', 'Chavez', 'ShellyChavez@glumer.com', '737 South Street Irmo, SC 29063');
INSERT INTO Customer VALUES(89, 'Dianna', 'Lee', 'DiannaLee@heanib.com', '13 James Street Thornton, CO 80241');
INSERT INTO Customer VALUES(90, 'Johnnie', 'Holland', 'JohnnieHolland@weigan.com', '270 Hickory Lane Anaheim, CA 92806');
INSERT INTO Customer VALUES(91, 'Garrett', 'Meyer', 'GarrettMeyer@gaoate.com', '547 Hamilton Street Depew, NY 14043');
INSERT INTO Customer VALUES(92, 'Frances', 'Bryan', 'FrancesBryan@vinaal.com', '157 Cleveland Avenue Tiffin, OH 44883');
INSERT INTO Customer VALUES(93, 'Terrence', 'Ingram', 'TerrenceIngram@sherna.com', '143 Chestnut Street Chester, PA 19013');
INSERT INTO Customer VALUES(94, 'Della', 'Jones', 'DellaJones@chocue.com', '353 Oak Lane Titusville, FL 32780');
INSERT INTO Customer VALUES(95, 'Cecil', 'Boyd', 'CecilBoyd@komorn.com', '299 4th Street West Nicholasville, KY 40356');
INSERT INTO Customer VALUES(96, 'Lorena', 'Hines', 'LorenaHines@tautal.com', '83 New Street Franklin Square, NY 11010');
INSERT INTO Customer VALUES(97, 'Timmy', 'Wolfe', 'TimmyWolfe@tahere.com', '799 Cedar Avenue Halethorpe, MD 21227');
INSERT INTO Customer VALUES(98, 'Timothy', 'Roberson', 'TimothyRoberson@ebends.com', '426 Hillside Avenue Pickerington, OH 43147');
INSERT INTO Customer VALUES(99, 'Gerald', 'Ruiz', 'GeraldRuiz@dompas.com', '582 Mill Street Villa Park, IL 60181');
