INSERT INTO PlayerMerchandisePlayer VALUES(81, 8, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(82, 8, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(83, 8, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(84, 9, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(85, 9, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(86, 9, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(87, 2, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(88, 2, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(89, 2, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(90, 23, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(91, 23, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(92, 23, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(93, 24, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(94, 24, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(95, 24, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(96, 1, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(97, 1, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(98, 1, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(99, 14, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(100, 14, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(101, 14, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(102, 0, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(103, 0, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(104, 0, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(105, 20, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(106, 20, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(107, 20, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(108, 4, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(109, 4, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(110, 4, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(111, 5, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(112, 5, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(113, 5, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(114, 13, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(115, 13, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(116, 13, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(117, 52, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(118, 52, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(119, 52, 'Cleveland Cavaliers');
INSERT INTO PlayerMerchandisePlayer VALUES(120, 15, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(121, 15, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(122, 15, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(123, 8, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(124, 8, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(125, 8, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(126, 20, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(127, 20, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(128, 20, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(129, 5, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(130, 5, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(131, 5, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(132, 10, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(133, 10, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(134, 10, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(135, 3, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(136, 3, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(137, 3, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(138, 6, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(139, 6, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(140, 6, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(141, 7, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(142, 7, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(143, 7, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(144, 92, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(145, 92, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(146, 92, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(147, 54, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(148, 54, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(149, 54, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(150, 24, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(151, 24, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(152, 24, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(153, 31, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(154, 31, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(155, 31, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(156, 4, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(157, 4, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(158, 4, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(159, 17, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(160, 17, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(161, 17, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(162, 55, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(163, 55, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(164, 55, 'Toronto Raptors');
INSERT INTO PlayerMerchandisePlayer VALUES(165, 0, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(166, 0, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(167, 0, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(168, 99, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(169, 99, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(170, 99, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(171, 28, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(172, 28, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(173, 28, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(174, 8, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(175, 8, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(176, 8, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(177, 90, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(178, 90, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(179, 90, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(180, 55, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(181, 55, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(182, 55, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(183, 41, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(184, 41, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(185, 41, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(186, 12, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(187, 12, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(188, 12, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(189, 36, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(190, 36, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(191, 36, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(192, 7, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(193, 7, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(194, 7, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(195, 4, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(196, 4, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(197, 4, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(198, 11, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(199, 11, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(200, 11, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(201, 13, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(202, 13, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(203, 13, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(204, 44, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(205, 44, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(206, 44, 'Boston Celtics');
INSERT INTO PlayerMerchandisePlayer VALUES(207, 1, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(208, 1, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(209, 1, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(210, 9, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(211, 9, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(212, 9, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(213, 7, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(214, 7, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(215, 7, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(216, 14, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(217, 14, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(218, 14, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(219, 40, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(220, 40, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(221, 40, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(222, 8, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(223, 8, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(224, 8, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(225, 4, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(226, 4, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(227, 4, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(228, 0, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(229, 0, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(230, 0, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(231, 5, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(232, 5, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(233, 5, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(234, 19, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(235, 19, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(236, 19, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(237, 3, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(238, 3, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(239, 3, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(240, 21, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(241, 21, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(242, 21, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(243, 20, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(244, 20, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(245, 20, 'Miami Heat');
INSERT INTO PlayerMerchandisePlayer VALUES(246, 24, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(247, 24, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(248, 24, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(249, 10, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(250, 10, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(251, 10, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(252, 12, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(253, 12, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(254, 12, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(255, 15, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(256, 15, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(257, 15, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(258, 26, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(259, 26, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(260, 26, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(261, 4, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(262, 4, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(263, 4, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(264, 31, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(265, 31, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(266, 31, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(267, 13, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(268, 13, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(269, 13, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(270, 17, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(271, 17, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(272, 17, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(273, 32, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(274, 32, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(275, 32, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(276, 25, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(277, 25, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(278, 25, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(279, 11, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(280, 11, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(281, 11, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(282, 22, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(283, 22, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(284, 22, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(285, 0, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(286, 0, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(287, 0, 'Atlanta Hawks');
INSERT INTO PlayerMerchandisePlayer VALUES(288, 5, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(289, 5, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(290, 5, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(291, 10, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(292, 10, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(293, 10, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(294, 25, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(295, 25, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(296, 25, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(297, 11, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(298, 11, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(299, 11, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(300, 13, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(301, 13, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(302, 13, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(303, 3, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(304, 3, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(305, 3, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(306, 27, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(307, 27, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(308, 27, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(309, 44, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(310, 44, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(311, 44, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(312, 28, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(313, 28, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(314, 28, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(315, 0, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(316, 0, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(317, 0, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(318, 40, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(319, 40, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(320, 40, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(321, 2, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(322, 2, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(323, 2, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(324, 33, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(325, 33, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(326, 33, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(327, 42, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(328, 42, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(329, 42, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(330, 1, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(331, 1, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(332, 1, 'Indiana Pacers');
INSERT INTO PlayerMerchandisePlayer VALUES(333, 5, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(334, 5, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(335, 5, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(336, 30, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(337, 30, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(338, 30, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(339, 12, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(340, 12, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(341, 12, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(342, 50, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(343, 50, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(344, 50, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(345, 9, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(346, 9, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(347, 9, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(348, 0, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(349, 0, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(350, 0, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(351, 25, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(352, 25, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(353, 25, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(354, 44, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(355, 44, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(356, 44, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(357, 14, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(358, 14, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(359, 14, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(360, 3, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(361, 3, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(362, 3, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(363, 1, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(364, 1, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(365, 1, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(366, 7, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(367, 7, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(368, 7, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(369, 15, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(370, 15, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(371, 15, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(372, 2, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(373, 2, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(374, 2, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(375, 40, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(376, 40, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(377, 40, 'Charlotte Hornets');
INSERT INTO PlayerMerchandisePlayer VALUES(378, 41, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(379, 41, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(380, 41, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(381, 0, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(382, 0, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(383, 0, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(384, 21, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(385, 21, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(386, 21, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(387, 34, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(388, 34, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(389, 34, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(390, 6, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(391, 6, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(392, 6, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(393, 16, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(394, 16, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(395, 16, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(396, 22, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(397, 22, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(398, 22, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(399, 7, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(400, 7, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(401, 7, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(402, 3, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(403, 3, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(404, 3, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(405, 44, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(406, 44, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(407, 44, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(408, 55, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(409, 55, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(410, 55, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(411, 13, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(412, 13, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(413, 13, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(414, 5, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(415, 5, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(416, 5, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(417, 1, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(418, 1, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(419, 1, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(420, 20, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(421, 20, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(422, 20, 'Chicago Bulls');
INSERT INTO PlayerMerchandisePlayer VALUES(423, 50, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(424, 50, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(425, 50, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(426, 12, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(427, 12, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(428, 12, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(429, 22, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(430, 22, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(431, 22, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(432, 25, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(433, 25, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(434, 25, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(435, 5, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(436, 5, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(437, 5, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(438, 8, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(439, 8, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(440, 8, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(441, 0, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(442, 0, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(443, 0, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(444, 32, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(445, 32, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(446, 32, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(447, 34, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(448, 34, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(449, 34, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(450, 6, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(451, 6, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(452, 6, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(453, 1, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(454, 1, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(455, 1, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(456, 3, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(457, 3, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(458, 3, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(459, 20, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(460, 20, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(461, 20, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(462, 13, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(463, 13, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(464, 13, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(465, 43, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(466, 43, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(467, 43, 'Detroit Pistons');
INSERT INTO PlayerMerchandisePlayer VALUES(468, 6, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(469, 6, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(470, 6, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(471, 3, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(472, 3, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(473, 3, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(474, 1, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(475, 1, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(476, 1, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(477, 8, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(478, 8, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(479, 8, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(480, 90, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(481, 90, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(482, 90, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(483, 13, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(484, 13, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(485, 13, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(486, 0, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(487, 0, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(488, 0, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(489, 5, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(490, 5, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(491, 5, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(492, 14, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(493, 14, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(494, 14, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(495, 42, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(496, 42, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(497, 42, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(498, 12, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(499, 12, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(500, 12, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(501, 22, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(502, 22, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(503, 22, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(504, 7, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(505, 7, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(506, 7, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(507, 17, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(508, 17, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(509, 17, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(510, 2, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(511, 2, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(512, 2, 'Washington Wizards');
INSERT INTO PlayerMerchandisePlayer VALUES(513, 3, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(514, 3, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(515, 3, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(516, 10, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(517, 10, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(518, 10, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(519, 0, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(520, 0, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(521, 0, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(522, 23, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(523, 23, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(524, 23, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(525, 7, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(526, 7, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(527, 7, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(528, 55, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(529, 55, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(530, 55, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(531, 11, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(532, 11, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(533, 11, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(534, 13, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(535, 13, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(536, 13, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(537, 44, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(538, 44, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(539, 44, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(540, 5, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(541, 5, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(542, 5, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(543, 4, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(544, 4, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(545, 4, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(546, 14, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(547, 14, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(548, 14, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(549, 9, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(550, 9, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(551, 9, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(552, 32, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(553, 32, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(554, 32, 'Orlando Magic');
INSERT INTO PlayerMerchandisePlayer VALUES(555, 4, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(556, 4, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(557, 4, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(558, 17, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(559, 17, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(560, 17, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(561, 7, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(562, 7, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(563, 7, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(564, 3, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(565, 3, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(566, 3, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(567, 11, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(568, 11, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(569, 11, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(570, 32, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(571, 32, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(572, 32, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(573, 2, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(574, 2, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(575, 2, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(576, 13, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(577, 13, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(578, 13, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(579, 8, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(580, 8, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(581, 8, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(582, 9, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(583, 9, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(584, 9, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(585, 6, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(586, 6, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(587, 6, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(588, 1, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(589, 1, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(590, 1, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(591, 42, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(592, 42, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(593, 42, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(594, 18, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(595, 18, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(596, 18, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(597, 23, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(598, 23, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(599, 23, 'New York Knicks');
INSERT INTO PlayerMerchandisePlayer VALUES(600, 34, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(601, 34, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(602, 34, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(603, 19, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(604, 19, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(605, 19, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(606, 5, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(607, 5, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(608, 5, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(609, 11, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(610, 11, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(611, 11, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(612, 31, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(613, 31, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(614, 31, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(615, 17, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(616, 17, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(617, 17, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(618, 3, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(619, 3, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(620, 3, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(621, 22, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(622, 22, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(623, 22, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(624, 15, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(625, 15, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(626, 15, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(627, 6, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(628, 6, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(629, 6, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(630, 77, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(631, 77, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(632, 77, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(633, 12, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(634, 12, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(635, 12, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(636, 18, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(637, 18, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(638, 18, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(639, 21, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(640, 21, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(641, 21, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(642, 20, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(643, 20, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(644, 20, 'Milwaukee Bucks');
INSERT INTO PlayerMerchandisePlayer VALUES(645, 44, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(646, 44, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(647, 44, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(648, 22, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(649, 22, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(650, 22, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(651, 21, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(652, 21, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(653, 21, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(654, 24, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(655, 24, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(656, 24, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(657, 2, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(658, 2, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(659, 2, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(660, 10, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(661, 10, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(662, 10, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(663, 0, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(664, 0, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(665, 0, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(666, 11, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(667, 11, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(668, 11, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(669, 1, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(670, 1, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(671, 1, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(672, 33, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(673, 33, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(674, 33, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(675, 41, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(676, 41, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(677, 41, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(678, 15, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(679, 15, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(680, 15, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(681, 30, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(682, 30, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(683, 30, 'Brooklyn Nets');
INSERT INTO PlayerMerchandisePlayer VALUES(684, 42, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(685, 42, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(686, 42, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(687, 0, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(688, 0, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(689, 0, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(690, 33, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(691, 33, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(692, 33, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(693, 21, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(694, 21, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(695, 21, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(696, 39, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(697, 39, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(698, 39, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(699, 22, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(700, 22, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(701, 22, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(702, 7, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(703, 7, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(704, 7, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(705, 5, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(706, 5, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(707, 5, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(708, 12, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(709, 12, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(710, 12, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(711, 4, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(712, 4, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(713, 4, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(714, 8, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(715, 8, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(716, 8, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(717, 1, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(718, 1, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(719, 1, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(720, 11, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(721, 11, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(722, 11, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(723, 31, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(724, 31, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(725, 31, 'Philadelphia 76ers');
INSERT INTO PlayerMerchandisePlayer VALUES(726, 1, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(727, 1, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(728, 1, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(729, 5, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(730, 5, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(731, 5, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(732, 21, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(733, 21, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(734, 21, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(735, 2, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(736, 2, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(737, 2, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(738, 34, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(739, 34, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(740, 34, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(741, 42, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(742, 42, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(743, 42, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(744, 23, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(745, 23, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(746, 23, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(747, 11, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(748, 11, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(749, 11, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(750, 50, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(751, 50, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(752, 50, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(753, 41, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(754, 41, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(755, 41, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(756, 27, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(757, 27, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(758, 27, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(759, 25, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(760, 25, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(761, 25, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(762, 7, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(763, 7, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(764, 7, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(765, 3, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(766, 3, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(767, 3, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(768, 8, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(769, 8, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(770, 8, 'Dallas Mavericks');
INSERT INTO PlayerMerchandisePlayer VALUES(771, 2, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(772, 2, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(773, 2, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(774, 12, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(775, 12, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(776, 12, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(777, 5, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(778, 5, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(779, 5, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(780, 21, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(781, 21, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(782, 21, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(783, 35, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(784, 35, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(785, 35, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(786, 8, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(787, 8, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(788, 8, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(789, 14, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(790, 14, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(791, 14, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(792, 15, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(793, 15, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(794, 15, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(795, 77, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(796, 77, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(797, 77, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(798, 3, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(799, 3, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(800, 3, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(801, 0, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(802, 0, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(803, 0, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(804, 1, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(805, 1, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(806, 1, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(807, 23, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(808, 23, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(809, 23, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(810, 9, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(811, 9, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(812, 9, 'Denver Nuggets');
INSERT INTO PlayerMerchandisePlayer VALUES(813, 19, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(814, 19, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(815, 19, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(816, 40, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(817, 40, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(818, 40, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(819, 12, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(820, 12, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(821, 12, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(822, 21, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(823, 21, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(824, 21, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(825, 30, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(826, 30, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(827, 30, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(828, 31, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(829, 31, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(830, 31, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(831, 23, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(832, 23, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(833, 23, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(834, 9, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(835, 9, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(836, 9, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(837, 34, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(838, 34, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(839, 34, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(840, 36, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(841, 36, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(842, 36, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(843, 20, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(844, 20, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(845, 20, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(846, 4, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(847, 4, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(848, 4, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(849, 5, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(850, 5, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(851, 5, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(852, 11, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(853, 11, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(854, 11, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(855, 18, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(856, 18, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(857, 18, 'Golden State Warriors');
INSERT INTO PlayerMerchandisePlayer VALUES(858, 1, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(859, 1, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(860, 1, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(861, 2, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(862, 2, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(863, 2, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(864, 33, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(865, 33, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(866, 33, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(867, 15, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(868, 15, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(869, 15, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(870, 7, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(871, 7, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(872, 7, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(873, 13, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(874, 13, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(875, 13, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(876, 35, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(877, 35, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(878, 35, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(879, 12, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(880, 12, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(881, 12, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(882, 6, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(883, 6, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(884, 6, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(885, 3, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(886, 3, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(887, 3, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(888, 32, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(889, 32, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(890, 32, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(891, 20, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(892, 20, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(893, 20, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(894, 5, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(895, 5, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(896, 5, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(897, 31, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(898, 31, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(899, 31, 'Houston Rockets');
INSERT INTO PlayerMerchandisePlayer VALUES(900, 45, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(901, 45, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(902, 45, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(903, 11, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(904, 11, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(905, 11, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(906, 22, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(907, 22, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(908, 22, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(909, 8, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(910, 8, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(911, 8, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(912, 32, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(913, 32, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(914, 32, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(915, 33, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(916, 33, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(917, 33, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(918, 6, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(919, 6, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(920, 6, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(921, 12, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(922, 12, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(923, 12, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(924, 3, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(925, 3, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(926, 3, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(927, 34, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(928, 34, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(929, 34, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(930, 9, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(931, 9, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(932, 9, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(933, 4, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(934, 4, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(935, 4, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(936, 25, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(937, 25, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(938, 25, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(939, 35, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(940, 35, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(941, 35, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(942, 30, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(943, 30, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(944, 30, 'Los Angeles Clippers');
INSERT INTO PlayerMerchandisePlayer VALUES(945, 2, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(946, 2, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(947, 2, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(948, 28, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(949, 28, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(950, 28, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(951, 3, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(952, 3, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(953, 3, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(954, 24, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(955, 24, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(956, 24, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(957, 6, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(958, 6, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(959, 6, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(960, 17, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(961, 17, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(962, 17, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(963, 9, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(964, 9, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(965, 9, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(966, 4, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(967, 4, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(968, 4, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(969, 7, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(970, 7, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(971, 7, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(972, 30, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(973, 30, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(974, 30, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(975, 1, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(976, 1, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(977, 1, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(978, 50, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(979, 50, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(980, 50, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(981, 23, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(982, 23, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(983, 23, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(984, 37, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(985, 37, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(986, 37, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(987, 0, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(988, 0, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(989, 0, 'Los Angeles Lakers');
INSERT INTO PlayerMerchandisePlayer VALUES(990, 3, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(991, 3, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(992, 3, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(993, 9, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(994, 9, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(995, 9, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(996, 7, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(997, 7, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(998, 7, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(999, 22, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1000, 22, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1001, 22, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1002, 15, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1003, 15, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1004, 15, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1005, 6, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1006, 6, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1007, 6, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1008, 11, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1009, 11, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1010, 11, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1011, 8, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1012, 8, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1013, 8, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1014, 33, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1015, 33, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1016, 33, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1017, 0, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1018, 0, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1019, 0, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1020, 19, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1021, 19, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1022, 19, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1023, 10, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1024, 10, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1025, 10, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1026, 50, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1027, 50, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1028, 50, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1029, 1, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1030, 1, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1031, 1, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1032, 34, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1033, 34, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1034, 34, 'Memphis Grizzlies');
INSERT INTO PlayerMerchandisePlayer VALUES(1035, 88, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1036, 88, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1037, 88, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1038, 5, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1039, 5, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1040, 5, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1041, 21, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1042, 21, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1043, 21, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1044, 1, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1045, 1, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1046, 1, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1047, 8, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1048, 8, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1049, 8, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1050, 23, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1051, 23, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1052, 23, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1053, 15, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1054, 15, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1055, 15, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1056, 33, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1057, 33, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1058, 33, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1059, 14, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1060, 14, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1061, 14, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1062, 12, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1063, 12, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1064, 12, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1065, 9, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1066, 9, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1067, 9, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1068, 10, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1069, 10, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1070, 10, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1071, 32, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1072, 32, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1073, 32, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1074, 22, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1075, 22, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1076, 22, 'Minnesota Timberwolves');
INSERT INTO PlayerMerchandisePlayer VALUES(1077, 42, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1078, 42, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1079, 42, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1080, 33, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1081, 33, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1082, 33, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1083, 3, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1084, 3, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1085, 3, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1086, 8, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1087, 8, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1088, 8, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1089, 30, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1090, 30, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1091, 30, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1092, 44, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1093, 44, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1094, 44, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1095, 23, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1096, 23, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1097, 23, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1098, 31, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1099, 31, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1100, 31, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1101, 16, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1102, 16, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1103, 16, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1104, 1, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1105, 1, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1106, 1, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1107, 15, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1108, 15, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1109, 15, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1110, 10, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1111, 10, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1112, 10, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1113, 11, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1114, 11, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1115, 11, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1116, 5, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1117, 5, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1118, 5, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1119, 20, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1120, 20, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1121, 20, 'New Orleans Pelicans');
INSERT INTO PlayerMerchandisePlayer VALUES(1122, 12, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1123, 12, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1124, 12, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1125, 4, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1126, 4, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1127, 4, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1128, 35, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1129, 35, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1130, 35, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1131, 6, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1132, 6, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1133, 6, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1134, 34, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1135, 34, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1136, 34, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1137, 9, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1138, 9, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1139, 9, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1140, 11, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1141, 11, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1142, 11, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1143, 33, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1144, 33, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1145, 33, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1146, 2, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1147, 2, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1148, 2, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1149, 22, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1150, 22, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1151, 22, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1152, 21, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1153, 21, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1154, 21, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1155, 5, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1156, 5, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1157, 5, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1158, 3, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1159, 3, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1160, 3, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1161, 0, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1162, 0, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1163, 0, 'Oklahoma City Thunder');
INSERT INTO PlayerMerchandisePlayer VALUES(1164, 2, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1165, 2, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1166, 2, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1167, 1, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1168, 1, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1169, 1, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1170, 4, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1171, 4, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1172, 4, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1173, 20, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1174, 20, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1175, 20, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1176, 43, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1177, 43, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1178, 43, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1179, 23, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1180, 23, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1181, 23, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1182, 3, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1183, 3, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1184, 3, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1185, 21, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1186, 21, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1187, 21, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1188, 30, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1189, 30, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1190, 30, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1191, 25, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1192, 25, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1193, 25, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1194, 14, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1195, 14, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1196, 14, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1197, 35, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1198, 35, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1199, 35, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1200, 17, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1201, 17, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1202, 17, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1203, 12, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1204, 12, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1205, 12, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1206, 10, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1207, 10, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1208, 10, 'Phoenix Suns');
INSERT INTO PlayerMerchandisePlayer VALUES(1209, 34, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1210, 34, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1211, 34, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1212, 8, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1213, 8, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1214, 8, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1215, 5, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1216, 5, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1217, 5, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1218, 23, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1219, 23, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1220, 23, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1221, 17, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1222, 17, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1223, 17, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1224, 4, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1225, 4, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1226, 4, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1227, 9, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1228, 9, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1229, 9, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1230, 35, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1231, 35, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1232, 35, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1233, 11, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1234, 11, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1235, 11, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1236, 0, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1237, 0, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1238, 0, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1239, 3, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1240, 3, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1241, 3, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1242, 44, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1243, 44, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1244, 44, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1245, 24, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1246, 24, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1247, 24, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1248, 2, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1249, 2, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1250, 2, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1251, 21, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1252, 21, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1253, 21, 'Portland Trail Blazers');
INSERT INTO PlayerMerchandisePlayer VALUES(1254, 13, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1255, 13, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1256, 13, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1257, 5, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1258, 5, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1259, 5, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1260, 3, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1261, 3, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1262, 3, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1263, 31, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1264, 31, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1265, 31, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1266, 18, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1267, 18, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1268, 18, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1269, 0, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1270, 0, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1271, 0, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1272, 7, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1273, 7, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1274, 7, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1275, 15, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1276, 15, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1277, 15, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1278, 30, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1279, 30, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1280, 30, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1281, 26, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1282, 26, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1283, 26, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1284, 8, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1285, 8, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1286, 8, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1287, 41, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1288, 41, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1289, 41, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1290, 23, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1291, 23, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1292, 23, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1293, 25, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1294, 25, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1295, 25, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1296, 9, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1297, 9, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1298, 9, 'Sacramento Kings');
INSERT INTO PlayerMerchandisePlayer VALUES(1299, 12, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1300, 12, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1301, 12, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1302, 1, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1303, 1, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1304, 1, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1305, 15, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1306, 15, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1307, 15, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1308, 18, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1309, 18, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1310, 18, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1311, 33, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1312, 33, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1313, 33, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1314, 21, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1315, 21, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1316, 21, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1317, 20, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1318, 20, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1319, 20, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1320, 14, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1321, 14, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1322, 14, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1323, 2, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1324, 2, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1325, 2, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1326, 40, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1327, 40, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1328, 40, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1329, 3, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1330, 3, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1331, 3, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1332, 8, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1333, 8, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1334, 8, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1335, 9, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1336, 9, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1337, 9, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1338, 17, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1339, 17, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1340, 17, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1341, 30, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1342, 30, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1343, 30, 'San Antonio Spurs');
INSERT INTO PlayerMerchandisePlayer VALUES(1344, 33, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1345, 33, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1346, 33, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1347, 3, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1348, 3, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1349, 3, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1350, 10, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1351, 10, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1352, 10, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1353, 11, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1354, 11, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1355, 11, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1356, 15, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1357, 15, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1358, 15, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1359, 27, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1360, 27, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1361, 27, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1362, 20, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1363, 20, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1364, 20, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1365, 5, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1366, 5, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1367, 5, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1368, 2, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1369, 2, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1370, 2, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1371, 23, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1372, 23, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1373, 23, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1374, 41, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1375, 41, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1376, 41, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1377, 8, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1378, 8, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1379, 8, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1380, 25, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1381, 25, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1382, 25, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1383, 21, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1384, 21, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1385, 21, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1386, 24, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1387, 24, 'Utah Jazz');
INSERT INTO PlayerMerchandisePlayer VALUES(1388, 24, 'Utah Jazz');