INSERT INTO PlayerMerchandisePlayer VALUES(81, 10, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(82, 10, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(83, 10, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(84, 0, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(85, 0, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(86, 0, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(87, 22, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(88, 22, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(89, 22, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(90, 11, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(91, 11, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(92, 11, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(93, 25, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(94, 25, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(95, 25, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(96, 32, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(97, 32, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(98, 32, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(99, 17, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(100, 17, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(101, 17, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(102, 13, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(103, 13, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(104, 13, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(105, 31, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(106, 31, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(107, 31, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(108, 4, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(109, 4, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(110, 4, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(111, 26, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(112, 26, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(113, 26, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(114, 15, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(115, 15, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(116, 15, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(117, 12, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(118, 12, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(119, 12, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(120, 24, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(121, 24, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(122, 24, 'Atlanta Hawks ');
INSERT INTO PlayerMerchandisePlayer VALUES(123, 4, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(124, 4, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(125, 4, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(126, 99, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(127, 99, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(128, 99, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(129, 28, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(130, 28, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(131, 28, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(132, 8, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(133, 8, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(134, 8, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(135, 90, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(136, 90, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(137, 90, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(138, 55, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(139, 55, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(140, 55, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(141, 41, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(142, 41, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(143, 41, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(144, 12, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(145, 12, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(146, 12, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(147, 36, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(148, 36, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(149, 36, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(150, 7, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(151, 7, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(152, 7, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(153, 11, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(154, 11, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(155, 11, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(156, 13, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(157, 13, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(158, 13, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(159, 44, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(160, 44, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(161, 44, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(162, 0, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(163, 0, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(164, 0, 'Boston Celtics ');
INSERT INTO PlayerMerchandisePlayer VALUES(165, 15, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(166, 15, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(167, 15, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(168, 44, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(169, 44, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(170, 44, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(171, 22, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(172, 22, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(173, 22, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(174, 21, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(175, 21, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(176, 21, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(177, 24, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(178, 24, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(179, 24, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(180, 2, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(181, 2, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(182, 2, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(183, 10, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(184, 10, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(185, 10, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(186, 0, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(187, 0, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(188, 0, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(189, 11, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(190, 11, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(191, 11, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(192, 1, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(193, 1, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(194, 1, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(195, 33, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(196, 33, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(197, 33, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(198, 41, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(199, 41, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(200, 41, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(201, 30, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(202, 30, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(203, 30, 'Brooklyn Nets ');
INSERT INTO PlayerMerchandisePlayer VALUES(204, 2, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(205, 2, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(206, 2, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(207, 5, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(208, 5, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(209, 5, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(210, 30, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(211, 30, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(212, 30, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(213, 12, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(214, 12, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(215, 12, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(216, 50, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(217, 50, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(218, 50, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(219, 9, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(220, 9, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(221, 9, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(222, 0, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(223, 0, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(224, 0, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(225, 25, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(226, 25, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(227, 25, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(228, 44, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(229, 44, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(230, 44, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(231, 14, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(232, 14, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(233, 14, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(234, 3, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(235, 3, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(236, 3, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(237, 1, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(238, 1, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(239, 1, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(240, 7, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(241, 7, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(242, 7, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(243, 15, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(244, 15, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(245, 15, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(246, 40, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(247, 40, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(248, 40, 'Charlotte Hornets ');
INSERT INTO PlayerMerchandisePlayer VALUES(249, 20, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(250, 20, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(251, 20, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(252, 1, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(253, 1, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(254, 1, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(255, 5, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(256, 5, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(257, 5, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(258, 13, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(259, 13, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(260, 13, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(261, 55, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(262, 55, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(263, 55, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(264, 44, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(265, 44, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(266, 44, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(267, 3, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(268, 3, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(269, 3, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(270, 7, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(271, 7, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(272, 7, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(273, 22, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(274, 22, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(275, 22, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(276, 16, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(277, 16, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(278, 16, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(279, 6, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(280, 6, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(281, 6, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(282, 34, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(283, 34, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(284, 34, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(285, 21, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(286, 21, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(287, 21, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(288, 0, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(289, 0, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(290, 0, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(291, 41, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(292, 41, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(293, 41, 'Chicago Bulls ');
INSERT INTO PlayerMerchandisePlayer VALUES(294, 23, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(295, 23, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(296, 23, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(297, 13, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(298, 13, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(299, 13, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(300, 5, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(301, 5, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(302, 5, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(303, 4, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(304, 4, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(305, 4, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(306, 20, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(307, 20, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(308, 20, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(309, 12, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(310, 12, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(311, 12, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(312, 0, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(313, 0, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(314, 0, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(315, 14, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(316, 14, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(317, 14, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(318, 1, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(319, 1, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(320, 1, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(321, 24, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(322, 24, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(323, 24, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(324, 52, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(325, 52, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(326, 52, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(327, 2, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(328, 2, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(329, 2, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(330, 9, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(331, 9, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(332, 9, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(333, 8, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(334, 8, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(335, 8, 'Cleveland Cavaliers ');
INSERT INTO PlayerMerchandisePlayer VALUES(336, 1, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(337, 1, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(338, 1, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(339, 8, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(340, 8, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(341, 8, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(342, 3, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(343, 3, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(344, 3, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(345, 7, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(346, 7, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(347, 7, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(348, 25, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(349, 25, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(350, 25, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(351, 27, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(352, 27, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(353, 27, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(354, 41, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(355, 41, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(356, 41, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(357, 50, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(358, 50, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(359, 50, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(360, 11, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(361, 11, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(362, 11, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(363, 23, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(364, 23, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(365, 23, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(366, 42, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(367, 42, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(368, 42, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(369, 34, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(370, 34, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(371, 34, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(372, 2, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(373, 2, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(374, 2, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(375, 21, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(376, 21, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(377, 21, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(378, 5, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(379, 5, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(380, 5, 'Dallas Mavericks ');
INSERT INTO PlayerMerchandisePlayer VALUES(381, 9, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(382, 9, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(383, 9, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(384, 0, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(385, 0, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(386, 0, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(387, 12, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(388, 12, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(389, 12, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(390, 5, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(391, 5, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(392, 5, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(393, 21, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(394, 21, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(395, 21, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(396, 35, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(397, 35, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(398, 35, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(399, 8, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(400, 8, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(401, 8, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(402, 14, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(403, 14, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(404, 14, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(405, 15, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(406, 15, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(407, 15, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(408, 77, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(409, 77, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(410, 77, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(411, 3, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(412, 3, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(413, 3, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(414, 2, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(415, 2, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(416, 2, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(417, 1, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(418, 1, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(419, 1, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(420, 23, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(421, 23, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(422, 23, 'Denver Nuggets ');
INSERT INTO PlayerMerchandisePlayer VALUES(423, 22, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(424, 22, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(425, 22, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(426, 50, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(427, 50, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(428, 50, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(429, 12, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(430, 12, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(431, 12, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(432, 43, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(433, 43, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(434, 43, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(435, 13, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(436, 13, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(437, 13, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(438, 20, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(439, 20, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(440, 20, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(441, 3, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(442, 3, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(443, 3, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(444, 1, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(445, 1, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(446, 1, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(447, 6, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(448, 6, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(449, 6, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(450, 34, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(451, 34, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(452, 34, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(453, 32, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(454, 32, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(455, 32, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(456, 0, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(457, 0, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(458, 0, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(459, 8, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(460, 8, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(461, 8, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(462, 5, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(463, 5, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(464, 5, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(465, 25, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(466, 25, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(467, 25, 'Detroit Pistons ');
INSERT INTO PlayerMerchandisePlayer VALUES(468, 34, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(469, 34, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(470, 34, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(471, 18, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(472, 18, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(473, 18, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(474, 11, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(475, 11, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(476, 11, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(477, 5, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(478, 5, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(479, 5, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(480, 4, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(481, 4, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(482, 4, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(483, 20, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(484, 20, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(485, 20, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(486, 36, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(487, 36, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(488, 36, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(489, 9, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(490, 9, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(491, 9, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(492, 23, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(493, 23, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(494, 23, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(495, 31, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(496, 31, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(497, 31, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(498, 30, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(499, 30, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(500, 30, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(501, 21, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(502, 21, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(503, 21, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(504, 12, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(505, 12, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(506, 12, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(507, 40, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(508, 40, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(509, 40, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(510, 19, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(511, 19, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(512, 19, 'Golden State Warriors ');
INSERT INTO PlayerMerchandisePlayer VALUES(513, 5, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(514, 5, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(515, 5, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(516, 31, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(517, 31, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(518, 31, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(519, 1, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(520, 1, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(521, 1, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(522, 2, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(523, 2, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(524, 2, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(525, 33, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(526, 33, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(527, 33, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(528, 15, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(529, 15, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(530, 15, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(531, 7, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(532, 7, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(533, 7, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(534, 13, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(535, 13, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(536, 13, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(537, 35, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(538, 35, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(539, 35, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(540, 12, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(541, 12, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(542, 12, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(543, 6, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(544, 6, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(545, 6, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(546, 3, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(547, 3, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(548, 3, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(549, 32, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(550, 32, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(551, 32, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(552, 20, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(553, 20, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(554, 20, 'Houston Rockets ');
INSERT INTO PlayerMerchandisePlayer VALUES(555, 10, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(556, 10, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(557, 10, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(558, 25, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(559, 25, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(560, 25, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(561, 1, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(562, 1, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(563, 1, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(564, 42, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(565, 42, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(566, 42, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(567, 33, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(568, 33, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(569, 33, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(570, 2, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(571, 2, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(572, 2, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(573, 40, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(574, 40, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(575, 40, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(576, 0, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(577, 0, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(578, 0, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(579, 5, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(580, 5, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(581, 5, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(582, 28, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(583, 28, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(584, 28, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(585, 44, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(586, 44, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(587, 44, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(588, 27, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(589, 27, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(590, 27, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(591, 3, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(592, 3, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(593, 3, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(594, 13, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(595, 13, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(596, 13, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(597, 11, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(598, 11, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(599, 11, 'Indiana Pacers ');
INSERT INTO PlayerMerchandisePlayer VALUES(600, 45, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(601, 45, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(602, 45, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(603, 30, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(604, 30, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(605, 30, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(606, 35, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(607, 35, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(608, 35, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(609, 25, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(610, 25, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(611, 25, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(612, 4, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(613, 4, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(614, 4, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(615, 9, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(616, 9, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(617, 9, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(618, 34, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(619, 34, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(620, 34, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(621, 3, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(622, 3, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(623, 3, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(624, 12, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(625, 12, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(626, 12, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(627, 6, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(628, 6, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(629, 6, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(630, 33, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(631, 33, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(632, 33, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(633, 32, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(634, 32, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(635, 32, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(636, 8, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(637, 8, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(638, 8, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(639, 22, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(640, 22, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(641, 22, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(642, 11, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(643, 11, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(644, 11, 'Los Angeles Clippers ');
INSERT INTO PlayerMerchandisePlayer VALUES(645, 2, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(646, 2, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(647, 2, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(648, 0, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(649, 0, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(650, 0, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(651, 37, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(652, 37, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(653, 37, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(654, 23, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(655, 23, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(656, 23, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(657, 50, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(658, 50, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(659, 50, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(660, 1, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(661, 1, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(662, 1, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(663, 30, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(664, 30, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(665, 30, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(666, 7, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(667, 7, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(668, 7, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(669, 4, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(670, 4, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(671, 4, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(672, 9, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(673, 9, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(674, 9, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(675, 17, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(676, 17, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(677, 17, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(678, 6, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(679, 6, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(680, 6, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(681, 24, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(682, 24, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(683, 24, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(684, 3, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(685, 3, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(686, 3, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(687, 28, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(688, 28, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(689, 28, 'Los Angeles Lakers ');
INSERT INTO PlayerMerchandisePlayer VALUES(690, 33, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(691, 33, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(692, 33, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(693, 3, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(694, 3, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(695, 3, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(696, 9, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(697, 9, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(698, 9, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(699, 7, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(700, 7, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(701, 7, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(702, 22, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(703, 22, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(704, 22, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(705, 15, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(706, 15, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(707, 15, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(708, 6, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(709, 6, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(710, 6, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(711, 11, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(712, 11, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(713, 11, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(714, 8, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(715, 8, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(716, 8, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(717, 0, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(718, 0, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(719, 0, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(720, 19, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(721, 19, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(722, 19, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(723, 10, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(724, 10, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(725, 10, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(726, 50, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(727, 50, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(728, 50, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(729, 1, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(730, 1, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(731, 1, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(732, 34, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(733, 34, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(734, 34, 'Memphis Grizzlies ');
INSERT INTO PlayerMerchandisePlayer VALUES(735, 1, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(736, 1, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(737, 1, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(738, 9, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(739, 9, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(740, 9, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(741, 7, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(742, 7, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(743, 7, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(744, 14, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(745, 14, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(746, 14, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(747, 40, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(748, 40, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(749, 40, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(750, 2, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(751, 2, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(752, 2, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(753, 8, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(754, 8, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(755, 8, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(756, 4, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(757, 4, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(758, 4, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(759, 0, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(760, 0, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(761, 0, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(762, 5, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(763, 5, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(764, 5, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(765, 19, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(766, 19, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(767, 19, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(768, 3, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(769, 3, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(770, 3, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(771, 21, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(772, 21, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(773, 21, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(774, 20, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(775, 20, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(776, 20, 'Miami Heat ');
INSERT INTO PlayerMerchandisePlayer VALUES(777, 12, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(778, 12, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(779, 12, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(780, 34, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(781, 34, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(782, 34, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(783, 19, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(784, 19, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(785, 19, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(786, 5, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(787, 5, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(788, 5, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(789, 11, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(790, 11, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(791, 11, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(792, 31, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(793, 31, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(794, 31, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(795, 17, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(796, 17, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(797, 17, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(798, 3, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(799, 3, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(800, 3, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(801, 22, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(802, 22, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(803, 22, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(804, 15, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(805, 15, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(806, 15, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(807, 6, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(808, 6, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(809, 6, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(810, 77, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(811, 77, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(812, 77, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(813, 18, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(814, 18, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(815, 18, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(816, 21, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(817, 21, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(818, 21, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(819, 20, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(820, 20, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(821, 20, 'Milwaukee Bucks ');
INSERT INTO PlayerMerchandisePlayer VALUES(822, 88, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(823, 88, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(824, 88, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(825, 5, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(826, 5, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(827, 5, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(828, 21, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(829, 21, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(830, 21, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(831, 1, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(832, 1, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(833, 1, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(834, 8, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(835, 8, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(836, 8, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(837, 23, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(838, 23, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(839, 23, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(840, 15, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(841, 15, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(842, 15, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(843, 33, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(844, 33, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(845, 33, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(846, 14, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(847, 14, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(848, 14, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(849, 12, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(850, 12, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(851, 12, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(852, 9, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(853, 9, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(854, 9, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(855, 22, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(856, 22, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(857, 22, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(858, 10, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(859, 10, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(860, 10, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(861, 32, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(862, 32, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(863, 32, 'Minnesota Timberwolves ');
INSERT INTO PlayerMerchandisePlayer VALUES(864, 20, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(865, 20, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(866, 20, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(867, 11, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(868, 11, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(869, 11, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(870, 5, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(871, 5, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(872, 5, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(873, 42, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(874, 42, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(875, 42, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(876, 33, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(877, 33, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(878, 33, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(879, 3, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(880, 3, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(881, 3, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(882, 8, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(883, 8, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(884, 8, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(885, 30, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(886, 30, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(887, 30, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(888, 44, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(889, 44, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(890, 44, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(891, 23, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(892, 23, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(893, 23, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(894, 31, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(895, 31, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(896, 31, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(897, 16, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(898, 16, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(899, 16, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(900, 1, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(901, 1, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(902, 1, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(903, 15, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(904, 15, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(905, 15, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(906, 10, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(907, 10, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(908, 10, 'New Orleans Pelicans ');
INSERT INTO PlayerMerchandisePlayer VALUES(909, 18, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(910, 18, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(911, 18, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(912, 4, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(913, 4, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(914, 4, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(915, 17, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(916, 17, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(917, 17, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(918, 7, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(919, 7, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(920, 7, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(921, 3, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(922, 3, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(923, 3, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(924, 11, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(925, 11, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(926, 11, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(927, 32, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(928, 32, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(929, 32, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(930, 2, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(931, 2, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(932, 2, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(933, 13, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(934, 13, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(935, 13, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(936, 8, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(937, 8, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(938, 8, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(939, 9, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(940, 9, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(941, 9, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(942, 6, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(943, 6, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(944, 6, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(945, 1, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(946, 1, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(947, 1, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(948, 42, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(949, 42, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(950, 42, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(951, 23, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(952, 23, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(953, 23, 'New York Knicks ');
INSERT INTO PlayerMerchandisePlayer VALUES(954, 0, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(955, 0, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(956, 0, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(957, 3, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(958, 3, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(959, 3, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(960, 5, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(961, 5, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(962, 5, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(963, 21, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(964, 21, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(965, 21, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(966, 22, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(967, 22, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(968, 22, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(969, 2, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(970, 2, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(971, 2, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(972, 33, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(973, 33, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(974, 33, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(975, 11, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(976, 11, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(977, 11, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(978, 9, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(979, 9, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(980, 9, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(981, 34, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(982, 34, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(983, 34, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(984, 6, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(985, 6, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(986, 6, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(987, 35, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(988, 35, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(989, 35, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(990, 4, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(991, 4, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(992, 4, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(993, 12, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(994, 12, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(995, 12, 'Oklahoma City Thunder ');
INSERT INTO PlayerMerchandisePlayer VALUES(996, 4, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(997, 4, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(998, 4, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(999, 8, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1000, 8, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1001, 8, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1002, 3, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1003, 3, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1004, 3, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1005, 10, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1006, 10, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1007, 10, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1008, 0, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1009, 0, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1010, 0, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1011, 23, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1012, 23, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1013, 23, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1014, 7, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1015, 7, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1016, 7, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1017, 55, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1018, 55, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1019, 55, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1020, 11, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1021, 11, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1022, 11, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1023, 13, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1024, 13, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1025, 13, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1026, 44, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1027, 44, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1028, 44, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1029, 5, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1030, 5, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1031, 5, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1032, 14, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1033, 14, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1034, 14, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1035, 9, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1036, 9, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1037, 9, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1038, 32, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1039, 32, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1040, 32, 'Orlando Magic ');
INSERT INTO PlayerMerchandisePlayer VALUES(1041, 42, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1042, 42, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1043, 42, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1044, 11, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1045, 11, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1046, 11, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1047, 1, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1048, 1, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1049, 1, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1050, 8, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1051, 8, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1052, 8, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1053, 4, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1054, 4, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1055, 4, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1056, 12, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1057, 12, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1058, 12, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1059, 5, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1060, 5, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1061, 5, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1062, 7, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1063, 7, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1064, 7, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1065, 22, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1066, 22, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1067, 22, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1068, 39, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1069, 39, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1070, 39, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1071, 21, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1072, 21, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1073, 21, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1074, 33, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1075, 33, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1076, 33, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1077, 0, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1078, 0, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1079, 0, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1080, 31, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1081, 31, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1082, 31, 'Philadelphia 76ers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1083, 20, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1084, 20, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1085, 20, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1086, 43, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1087, 43, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1088, 43, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1089, 4, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1090, 4, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1091, 4, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1092, 1, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1093, 1, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1094, 1, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1095, 2, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1096, 2, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1097, 2, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1098, 10, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1099, 10, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1100, 10, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1101, 12, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1102, 12, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1103, 12, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1104, 17, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1105, 17, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1106, 17, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1107, 35, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1108, 35, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1109, 35, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1110, 14, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1111, 14, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1112, 14, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1113, 25, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1114, 25, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1115, 25, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1116, 30, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1117, 30, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1118, 30, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1119, 21, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1120, 21, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1121, 21, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1122, 3, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1123, 3, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1124, 3, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1125, 23, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1126, 23, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1127, 23, 'Phoenix Suns ');
INSERT INTO PlayerMerchandisePlayer VALUES(1128, 44, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1129, 44, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1130, 44, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1131, 2, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1132, 2, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1133, 2, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1134, 8, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1135, 8, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1136, 8, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1137, 5, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1138, 5, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1139, 5, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1140, 23, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1141, 23, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1142, 23, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1143, 34, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1144, 34, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1145, 34, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1146, 17, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1147, 17, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1148, 17, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1149, 4, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1150, 4, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1151, 4, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1152, 9, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1153, 9, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1154, 9, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1155, 35, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1156, 35, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1157, 35, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1158, 11, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1159, 11, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1160, 11, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1161, 0, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1162, 0, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1163, 0, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1164, 3, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1165, 3, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1166, 3, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1167, 21, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1168, 21, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1169, 21, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1170, 24, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1171, 24, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1172, 24, 'Portland Trail Blazers ');
INSERT INTO PlayerMerchandisePlayer VALUES(1173, 5, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1174, 5, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1175, 5, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1176, 9, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1177, 9, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1178, 9, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1179, 25, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1180, 25, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1181, 25, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1182, 23, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1183, 23, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1184, 23, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1185, 41, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1186, 41, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1187, 41, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1188, 8, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1189, 8, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1190, 8, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1191, 26, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1192, 26, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1193, 26, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1194, 30, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1195, 30, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1196, 30, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1197, 15, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1198, 15, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1199, 15, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1200, 7, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1201, 7, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1202, 7, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1203, 0, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1204, 0, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1205, 0, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1206, 18, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1207, 18, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1208, 18, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1209, 31, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1210, 31, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1211, 31, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1212, 3, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1213, 3, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1214, 3, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1215, 13, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1216, 13, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1217, 13, 'Sacramento Kings ');
INSERT INTO PlayerMerchandisePlayer VALUES(1218, 12, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1219, 12, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1220, 12, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1221, 30, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1222, 30, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1223, 30, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1224, 17, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1225, 17, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1226, 17, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1227, 9, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1228, 9, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1229, 9, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1230, 8, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1231, 8, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1232, 8, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1233, 3, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1234, 3, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1235, 3, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1236, 40, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1237, 40, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1238, 40, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1239, 2, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1240, 2, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1241, 2, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1242, 14, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1243, 14, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1244, 14, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1245, 20, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1246, 20, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1247, 20, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1248, 21, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1249, 21, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1250, 21, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1251, 33, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1252, 33, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1253, 33, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1254, 18, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1255, 18, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1256, 18, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1257, 15, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1258, 15, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1259, 15, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1260, 1, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1261, 1, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1262, 1, 'San Antonio Spurs ');
INSERT INTO PlayerMerchandisePlayer VALUES(1263, 55, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1264, 55, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1265, 55, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1266, 17, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1267, 17, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1268, 17, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1269, 15, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1270, 15, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1271, 15, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1272, 8, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1273, 8, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1274, 8, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1275, 20, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1276, 20, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1277, 20, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1278, 5, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1279, 5, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1280, 5, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1281, 10, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1282, 10, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1283, 10, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1284, 3, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1285, 3, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1286, 3, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1287, 6, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1288, 6, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1289, 6, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1290, 7, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1291, 7, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1292, 7, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1293, 92, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1294, 92, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1295, 92, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1296, 54, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1297, 54, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1298, 54, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1299, 24, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1300, 24, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1301, 24, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1302, 31, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1303, 31, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1304, 31, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1305, 4, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1306, 4, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1307, 4, 'Toronto Raptors ');
INSERT INTO PlayerMerchandisePlayer VALUES(1308, 25, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1309, 25, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1310, 25, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1311, 24, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1312, 24, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1313, 24, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1314, 33, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1315, 33, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1316, 33, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1317, 3, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1318, 3, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1319, 3, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1320, 10, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1321, 10, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1322, 10, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1323, 11, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1324, 11, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1325, 11, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1326, 15, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1327, 15, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1328, 15, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1329, 27, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1330, 27, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1331, 27, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1332, 20, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1333, 20, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1334, 20, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1335, 5, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1336, 5, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1337, 5, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1338, 2, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1339, 2, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1340, 2, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1341, 23, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1342, 23, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1343, 23, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1344, 41, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1345, 41, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1346, 41, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1347, 8, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1348, 8, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1349, 8, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1350, 21, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1351, 21, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1352, 21, 'Utah Jazz ');
INSERT INTO PlayerMerchandisePlayer VALUES(1353, 3, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1354, 3, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1355, 3, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1356, 6, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1357, 6, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1358, 6, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1359, 1, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1360, 1, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1361, 1, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1362, 8, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1363, 8, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1364, 8, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1365, 90, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1366, 90, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1367, 90, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1368, 13, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1369, 13, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1370, 13, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1371, 21, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1372, 21, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1373, 21, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1374, 5, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1375, 5, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1376, 5, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1377, 14, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1378, 14, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1379, 14, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1380, 42, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1381, 42, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1382, 42, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1383, 12, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1384, 12, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1385, 12, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1386, 22, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1387, 22, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1388, 22, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1389, 7, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1390, 7, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1391, 7, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1392, 17, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1393, 17, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1394, 17, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1395, 2, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1396, 2, 'Washington Wizards ');
INSERT INTO PlayerMerchandisePlayer VALUES(1397, 2, 'Washington Wizards ');
