INSERT INTO Player VALUES(8, 0, 'Jonas', 'Jerebko', 'Boston Celtics');
INSERT INTO Player VALUES(90, 1, 'Amir', 'Johnson', 'Boston Celtics');
INSERT INTO Player VALUES(55, 2, 'Jordan', 'Mickey', 'Boston Celtics');
INSERT INTO Player VALUES(41, 3, 'Kelly', 'Olynyk', 'Boston Celtics');
INSERT INTO Player VALUES(12, 4, 'Terry', 'Rozier', 'Boston Celtics');
INSERT INTO Player VALUES(36, 5, 'Marcus', 'Smart', 'Boston Celtics');
INSERT INTO Player VALUES(7, 6, 'Jared', 'Sullinger', 'Boston Celtics');
INSERT INTO Player VALUES(4, 7, 'Isaiah', 'Thomas', 'Boston Celtics');
INSERT INTO Player VALUES(11, 8, 'Evan', 'Turner', 'Boston Celtics');
INSERT INTO Player VALUES(13, 9, 'James', 'Young', 'Boston Celtics');
INSERT INTO Player VALUES(44, 10, 'Tyler', 'Zeller', 'Boston Celtics');
INSERT INTO Player VALUES(1, 11, 'Justin', 'Anderson', 'Boston Celtics');
INSERT INTO Player VALUES(5, 12, 'JoseJuan', 'Barea', 'Boston Celtics');
INSERT INTO Player VALUES(21, 13, 'Jeremy', 'Evans', 'Boston Celtics');
INSERT INTO Player VALUES(2, 14, 'Raymond', 'Felton', 'Dallas Mavericks');
INSERT INTO Player VALUES(34, 15, 'Devin', 'Harris', 'Dallas Mavericks');
INSERT INTO Player VALUES(42, 16, 'David', 'Lee', 'Dallas Mavericks');
INSERT INTO Player VALUES(23, 17, 'Wesley', 'Matthews', 'Dallas Mavericks');
INSERT INTO Player VALUES(11, 18, 'JaVale', 'McGee', 'Dallas Mavericks');
INSERT INTO Player VALUES(50, 19, 'Salah', 'Mejri', 'Dallas Mavericks');
INSERT INTO Player VALUES(41, 20, 'Dirk', 'Nowitzki', 'Dallas Mavericks');
INSERT INTO Player VALUES(27, 21, 'Zaza', 'Pachulia', 'Dallas Mavericks');
INSERT INTO Player VALUES(25, 22, 'Chandler', 'Parsons', 'Dallas Mavericks');
INSERT INTO Player VALUES(7, 23, 'Dwight', 'Powell', 'Dallas Mavericks');
INSERT INTO Player VALUES(3, 24, 'Charlie', 'Villanueva', 'Dallas Mavericks');
INSERT INTO Player VALUES(8, 25, 'Deron', 'Williams', 'Dallas Mavericks');
INSERT INTO Player VALUES(44, 26, 'Bojan', 'Bogdanovic', 'Dallas Mavericks');
INSERT INTO Player VALUES(22, 27, 'Markel', 'Brown', 'Dallas Mavericks');
INSERT INTO Player VALUES(21, 28, 'Wayne', 'Ellington', 'Dallas Mavericks');
INSERT INTO Player VALUES(24, 29, 'Rondae', 'Hollis-Jefferson', 'Brooklyn Nets');
INSERT INTO Player VALUES(2, 30, 'Jarrett', 'Jack', 'Brooklyn Nets');
INSERT INTO Player VALUES(10, 31, 'Sergey', 'Karasev', 'Brooklyn Nets');
INSERT INTO Player VALUES(0, 32, 'Shane', 'Larkin', 'Brooklyn Nets');
INSERT INTO Player VALUES(11, 33, 'Brook', 'Lopez', 'Brooklyn Nets');
INSERT INTO Player VALUES(1, 34, 'Chris', 'McCullough', 'Brooklyn Nets');
INSERT INTO Player VALUES(33, 35, 'Willie', 'Reed', 'Brooklyn Nets');
INSERT INTO Player VALUES(41, 36, 'Thomas', 'Robinson', 'Brooklyn Nets');
INSERT INTO Player VALUES(15, 37, 'Donald', 'Sloan', 'Brooklyn Nets');
INSERT INTO Player VALUES(30, 38, 'Thaddeus', 'Young', 'Brooklyn Nets');
INSERT INTO Player VALUES(1, 39, 'Trevor', 'Ariza', 'Brooklyn Nets');
INSERT INTO Player VALUES(2, 40, 'Patrick', 'Beverley', 'Brooklyn Nets');
INSERT INTO Player VALUES(33, 41, 'Corey', 'Brewer', 'Brooklyn Nets');
INSERT INTO Player VALUES(15, 42, 'Clint', 'Capela', 'Houston Rockets');
INSERT INTO Player VALUES(7, 43, 'Sam', 'Dekker', 'Houston Rockets');
INSERT INTO Player VALUES(13, 44, 'James', 'Harden', 'Houston Rockets');
INSERT INTO Player VALUES(35, 45, 'Montrezl', 'Harrell', 'Houston Rockets');
INSERT INTO Player VALUES(12, 46, 'Dwight', 'Howard', 'Houston Rockets');
INSERT INTO Player VALUES(6, 47, 'Terrence', 'Jones', 'Houston Rockets');
INSERT INTO Player VALUES(3, 48, 'Ty', 'Lawson', 'Houston Rockets');
INSERT INTO Player VALUES(32, 49, 'K.J.', 'McDaniels', 'Houston Rockets');
INSERT INTO Player VALUES(20, 50, 'Donatas', 'Motiejunas', 'Houston Rockets');
INSERT INTO Player VALUES(5, 51, 'Josh', 'Smith', 'Houston Rockets');
INSERT INTO Player VALUES(31, 52, 'Jason', 'Terry', 'Houston Rockets');
INSERT INTO Player VALUES(10, 53, 'Marcus', 'Thornton', 'Houston Rockets');
INSERT INTO Player VALUES(4, 54, 'Arron', 'Afflalo', 'Houston Rockets');
INSERT INTO Player VALUES(17, 55, 'Lou', 'Amundson', 'Houston Rockets');
INSERT INTO Player VALUES(7, 56, 'Carmelo', 'Anthony', 'Houston Rockets');
INSERT INTO Player VALUES(3, 57, 'Jose', 'Calderon', 'New York Knicks');
INSERT INTO Player VALUES(11, 58, 'Cleanthony', 'Early', 'New York Knicks');
INSERT INTO Player VALUES(32, 59, 'Jimmer', 'Fredette', 'New York Knicks');
INSERT INTO Player VALUES(2, 60, 'Langston', 'Galloway', 'New York Knicks');
INSERT INTO Player VALUES(13, 61, 'Jerian', 'Grant', 'New York Knicks');
INSERT INTO Player VALUES(8, 62, 'Robin', 'Lopez', 'New York Knicks');
INSERT INTO Player VALUES(9, 63, 'Kyle', 'OQuinn', 'New York Knicks');
INSERT INTO Player VALUES(6, 64, 'Kristaps', 'Porzingis', 'New York Knicks');
INSERT INTO Player VALUES(1, 65, 'Kevin', 'Seraphin', 'New York Knicks');
INSERT INTO Player VALUES(42, 66, 'Lance', 'Thomas', 'New York Knicks');
INSERT INTO Player VALUES(18, 67, 'Sasha', 'Vujacic', 'New York Knicks');
INSERT INTO Player VALUES(23, 68, 'Derrick', 'Williams', 'New York Knicks');
INSERT INTO Player VALUES(3, 69, 'Jordan', 'Adams', 'New York Knicks');
INSERT INTO Player VALUES(9, 70, 'Tony', 'Allen', 'New York Knicks');
INSERT INTO Player VALUES(7, 71, 'Chris', 'Andersen', 'New York Knicks');
INSERT INTO Player VALUES(22, 72, 'Matt', 'Barnes', 'Memphis Grizzlies');
INSERT INTO Player VALUES(15, 73, 'Vince', 'Carter', 'Memphis Grizzlies');
INSERT INTO Player VALUES(6, 74, 'Mario', 'Chalmers', 'Memphis Grizzlies');
INSERT INTO Player VALUES(11, 75, 'Mike', 'Conley', 'Memphis Grizzlies');
INSERT INTO Player VALUES(8, 76, 'James', 'Ennis', 'Memphis Grizzlies');
INSERT INTO Player VALUES(33, 77, 'Marc', 'Gasol', 'Memphis Grizzlies');
INSERT INTO Player VALUES(0, 78, 'JaMychal', 'Green', 'Memphis Grizzlies');
INSERT INTO Player VALUES(19, 79, 'P.J.', 'Hairston', 'Memphis Grizzlies');
INSERT INTO Player VALUES(10, 80, 'Jarell', 'Martin', 'Memphis Grizzlies');
INSERT INTO Player VALUES(50, 81, 'Zach', 'Randolph', 'Memphis Grizzlies');
INSERT INTO Player VALUES(1, 82, 'Lance', 'Stephenson', 'Memphis Grizzlies');
INSERT INTO Player VALUES(34, 83, 'Brandan', 'Wright', 'Memphis Grizzlies');
INSERT INTO Player VALUES(42, 84, 'Elton', 'Brand', 'Memphis Grizzlies');
INSERT INTO Player VALUES(0, 85, 'Isaiah', 'Canaan', 'Memphis Grizzlies');
INSERT INTO Player VALUES(33, 86, 'Robert', 'Covington', 'Memphis Grizzlies');
INSERT INTO Player VALUES(21, 87, 'Joel', 'Embiid', 'Philadelphia 76ers');
INSERT INTO Player VALUES(39, 88, 'Jerami', 'Grant', 'Philadelphia 76ers');
INSERT INTO Player VALUES(22, 89, 'Richaun', 'Holmes', 'Philadelphia 76ers');
INSERT INTO Player VALUES(7, 90, 'Carl', 'Landry', 'Philadelphia 76ers');
INSERT INTO Player VALUES(5, 91, 'Kendall', 'Marshall', 'Philadelphia 76ers');
INSERT INTO Player VALUES(12, 92, 'T.J.', 'McConnell', 'Philadelphia 76ers');
INSERT INTO Player VALUES(4, 93, 'Nerlens', 'Noel', 'Philadelphia 76ers');
INSERT INTO Player VALUES(8, 94, 'Jahlil', 'Okafor', 'Philadelphia 76ers');
INSERT INTO Player VALUES(1, 95, 'Ish', 'Smith', 'Philadelphia 76ers');
INSERT INTO Player VALUES(11, 96, 'Nik', 'Stauskas', 'Philadelphia 76ers');
INSERT INTO Player VALUES(31, 97, 'Hollis', 'Thompson', 'Philadelphia 76ers');
INSERT INTO Player VALUES(42, 98, 'Alexis', 'Ajinca', 'Philadelphia 76ers');
INSERT INTO Player VALUES(33, 99, 'Ryan', 'Anderson', 'Philadelphia 76ers');
INSERT INTO Player VALUES(3, 100, 'Omer', 'Asik', 'Philadelphia 76ers');
INSERT INTO Player VALUES(8, 101, 'Luke', 'Babbitt', 'New Orleans Pelicans');
INSERT INTO Player VALUES(30, 102, 'Norris', 'Cole', 'New Orleans Pelicans');
INSERT INTO Player VALUES(44, 103, 'Dante', 'Cunningham', 'New Orleans Pelicans');
INSERT INTO Player VALUES(23, 104, 'Anthony', 'Davis', 'New Orleans Pelicans');
INSERT INTO Player VALUES(31, 105, 'Bryce', 'Dejean-Jones', 'New Orleans Pelicans');
INSERT INTO Player VALUES(16, 106, 'Toney', 'Douglas', 'New Orleans Pelicans');
INSERT INTO Player VALUES(1, 107, 'Tyreke', 'Evans', 'New Orleans Pelicans');
INSERT INTO Player VALUES(15, 108, 'Alonzo', 'Gee', 'New Orleans Pelicans');
INSERT INTO Player VALUES(10, 109, 'Eric', 'Gordon', 'New Orleans Pelicans');
INSERT INTO Player VALUES(11, 110, 'Jrue', 'Holiday', 'New Orleans Pelicans');
INSERT INTO Player VALUES(5, 111, 'Kendrick', 'Perkins', 'New Orleans Pelicans');
INSERT INTO Player VALUES(20, 112, 'Quincy', 'Pondexter', 'New Orleans Pelicans');
INSERT INTO Player VALUES(15, 113, 'Anthony', 'Bennett', 'New Orleans Pelicans');
INSERT INTO Player VALUES(8, 114, 'Bismack', 'Biyombo', 'New Orleans Pelicans');
INSERT INTO Player VALUES(20, 115, 'Bruno', 'Caboclo', 'New Orleans Pelicans');
INSERT INTO Player VALUES(5, 116, 'DeMarre', 'Carroll', 'Toronto Raptor');
INSERT INTO Player VALUES(10, 117, 'DeMar', 'DeRozan', 'Toronto Raptor');
INSERT INTO Player VALUES(3, 118, 'James', 'Johnson', 'Toronto Raptor');
INSERT INTO Player VALUES(6, 119, 'Cory', 'Joseph', 'Toronto Raptor');
INSERT INTO Player VALUES(7, 120, 'Kyle', 'Lowry', 'Toronto Raptor');
INSERT INTO Player VALUES(92, 121, 'Lucas', 'Nogueira', 'Toronto Raptor');
INSERT INTO Player VALUES(54, 122, 'Patrick', 'Patterson', 'Toronto Raptor');
INSERT INTO Player VALUES(24, 123, 'Norman', 'Powell', 'Toronto Raptor');
INSERT INTO Player VALUES(31, 124, 'Terrence', 'Ross', 'Toronto Raptor');
INSERT INTO Player VALUES(4, 125, 'Luis', 'Scola', 'Toronto Raptor');
INSERT INTO Player VALUES(17, 126, 'Jonas', 'Valanciunas', 'Toronto Raptor');
INSERT INTO Player VALUES(55, 127, 'Delon', 'Wright', 'Toronto Raptor');
INSERT INTO Player VALUES(12, 128, 'LaMarcus', 'Aldridge', 'Toronto Raptor');
INSERT INTO Player VALUES(1, 129, 'Kyle', 'Anderson', 'Toronto Raptor');
INSERT INTO Player VALUES(15, 130, 'Matt', 'Bonner', 'Toronto Raptor');
INSERT INTO Player VALUES(18, 131, 'Rasual', 'Butler', 'San Antonio Spurs');
INSERT INTO Player VALUES(33, 132, 'Boris', 'Diaw', 'San Antonio Spurs');
INSERT INTO Player VALUES(21, 133, 'Tim', 'Duncan', 'San Antonio Spurs');
INSERT INTO Player VALUES(20, 134, 'Manu', 'Ginobili', 'San Antonio Spurs');
INSERT INTO Player VALUES(14, 135, 'Danny', 'Green', 'San Antonio Spurs');
INSERT INTO Player VALUES(2, 136, 'Kawhi', 'Leonard', 'San Antonio Spurs');
INSERT INTO Player VALUES(40, 137, 'Boban', 'Marjanovic', 'San Antonio Spurs');
INSERT INTO Player VALUES(3, 138, 'Ray', 'McCallum', 'San Antonio Spurs');
INSERT INTO Player VALUES(8, 139, 'Patty', 'Mills', 'San Antonio Spurs');
INSERT INTO Player VALUES(9, 140, 'Tony', 'Parker', 'San Antonio Spurs');
INSERT INTO Player VALUES(17, 141, 'Jonathon', 'Simmons', 'San Antonio Spurs');
INSERT INTO Player VALUES(30, 142, 'David', 'West', 'San Antonio Spurs');
INSERT INTO Player VALUES(41, 143, 'Cameron', 'Bairstow', 'San Antonio Spurs');
INSERT INTO Player VALUES(0, 144, 'Aaron', 'Brooks', 'San Antonio Spurs');
INSERT INTO Player VALUES(21, 145, 'Jimmy', 'Butler', 'San Antonio Spurs');
INSERT INTO Player VALUES(34, 146, 'Mike', 'Dunleavy', 'Chicago Bulls');
INSERT INTO Player VALUES(6, 147, 'Cristiano', 'Felicio', 'Chicago Bulls');
INSERT INTO Player VALUES(16, 148, 'Pau', 'Gasol', 'Chicago Bulls');
INSERT INTO Player VALUES(22, 149, 'Taj', 'Gibson', 'Chicago Bulls');
INSERT INTO Player VALUES(7, 150, 'Justin', 'Holiday', 'Chicago Bulls');
INSERT INTO Player VALUES(3, 151, 'Doug', 'McDermott', 'Chicago Bulls');
INSERT INTO Player VALUES(44, 152, 'Nikola', 'Mirotic', 'Chicago Bulls');
INSERT INTO Player VALUES(55, 153, 'ETwaun', 'Moore', 'Chicago Bulls');
INSERT INTO Player VALUES(13, 154, 'Joakim', 'Noah', 'Chicago Bulls');
INSERT INTO Player VALUES(5, 155, 'Bobby', 'Portis', 'Chicago Bulls');
INSERT INTO Player VALUES(1, 156, 'Derrick', 'Rose', 'Chicago Bulls');
INSERT INTO Player VALUES(20, 157, 'Tony', 'Snell', 'Chicago Bulls');
INSERT INTO Player VALUES(0, 158, 'Darrell', 'Arthur', 'Chicago Bulls');
INSERT INTO Player VALUES(12, 159, 'D.J.', 'Augustin', 'Chicago Bulls');
INSERT INTO Player VALUES(5, 160, 'Will', 'Barton', 'Chicago Bulls');
INSERT INTO Player VALUES(21, 161, 'Wilson', 'Chandler', 'Denver Nuggets');
INSERT INTO Player VALUES(35, 162, 'Kenneth', 'Faried', 'Denver Nuggets');
INSERT INTO Player VALUES(8, 163, 'Danilo', 'Gallinari', 'Denver Nuggets');
INSERT INTO Player VALUES(14, 164, 'Gary', 'Harris', 'Denver Nuggets');
INSERT INTO Player VALUES(15, 165, 'Nikola', 'Jokic', 'Denver Nuggets');
INSERT INTO Player VALUES(77, 166, 'Joffrey', 'Lauvergne', 'Denver Nuggets');
INSERT INTO Player VALUES(3, 167, 'Mike', 'Miller', 'Denver Nuggets');
INSERT INTO Player VALUES(0, 168, 'Emmanuel', 'Mudiay', 'Denver Nuggets');
INSERT INTO Player VALUES(1, 169, 'Jameer', 'Nelson', 'Denver Nuggets');
INSERT INTO Player VALUES(23, 170, 'Jusuf', 'Nurkic', 'Denver Nuggets');
INSERT INTO Player VALUES(9, 171, 'JaKarr', 'Sampson', 'Denver Nuggets');
INSERT INTO Player VALUES(8, 172, 'Matthew', 'Dellavedova', 'Denver Nuggets');
INSERT INTO Player VALUES(9, 173, 'Channing', 'Frye', 'Denver Nuggets');
INSERT INTO Player VALUES(2, 174, 'Kyrie', 'Irving', 'Denver Nuggets');
INSERT INTO Player VALUES(23, 175, 'LeBron', 'James', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(24, 176, 'Richard', 'Jefferson', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(1, 177, 'James', 'Jones', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(14, 178, 'Sasha', 'Kaun', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(0, 179, 'Kevin', 'Love', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(12, 180, 'Jordan', 'McRae', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(20, 181, 'Timofey', 'Mozgov', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(4, 182, 'Iman', 'Shumpert', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(5, 183, 'J.R.', 'Smith', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(13, 184, 'Tristan', 'Thompson', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(52, 185, 'Mo', 'Williams', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(88, 186, 'Nemanja', 'Bjelica', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(5, 187, 'Gorgui', 'Dieng', 'Cleveland Cavaliers');
INSERT INTO Player VALUES(21, 188, 'Kevin', 'Garnett', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(1, 189, 'Tyus', 'Jones', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(8, 190, 'Zach', 'LaVine', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(23, 191, 'Kevin', 'Martin', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(15, 192, 'Shabazz', 'Muhammad', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(33, 193, 'Adreian', 'Payne', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(14, 194, 'Nikola', 'Pekovic', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(12, 195, 'Tayshaun', 'Prince', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(9, 196, 'Ricky', 'Rubio', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(10, 197, 'Damjan', 'Rudez', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(32, 198, 'Karl-Anthony', 'Towns', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(22, 199, 'Andrew', 'Wiggins', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(50, 200, 'Joel', 'Anthony', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(12, 201, 'Aron', 'Baynes', 'Minnesota Timberwolves');
INSERT INTO Player VALUES(22, 202, 'Steve', 'Blake', 'Detroit Pistons');
INSERT INTO Player VALUES(25, 203, 'Reggie', 'Bullock', 'Detroit Pistons');
INSERT INTO Player VALUES(5, 204, 'Kentavious', 'Caldwell-Pope', 'Detroit Pistons');
INSERT INTO Player VALUES(8, 205, 'Spencer', 'Dinwiddie', 'Detroit Pistons');
INSERT INTO Player VALUES(0, 206, 'Andre', 'Drummond', 'Detroit Pistons');
INSERT INTO Player VALUES(32, 207, 'Justin', 'Harper', 'Detroit Pistons');
INSERT INTO Player VALUES(34, 208, 'Tobias', 'Harris', 'Detroit Pistons');
INSERT INTO Player VALUES(6, 209, 'Darrun', 'Hilliard', 'Detroit Pistons');
INSERT INTO Player VALUES(1, 210, 'Reggie', 'Jackson', 'Detroit Pistons');
INSERT INTO Player VALUES(3, 211, 'Stanley', 'Johnson', 'Detroit Pistons');
INSERT INTO Player VALUES(20, 212, 'Jodie', 'Meeks', 'Detroit Pistons');
INSERT INTO Player VALUES(13, 213, 'Marcus', 'Morris', 'Detroit Pistons');
INSERT INTO Player VALUES(43, 214, 'Anthony', 'Tolliver', 'Detroit Pistons');
INSERT INTO Player VALUES(12, 215, 'Steven', 'Adams', 'Detroit Pistons');
INSERT INTO Player VALUES(4, 216, 'Nick', 'Collison', 'Detroit Pistons');
INSERT INTO Player VALUES(35, 217, 'Kevin', 'Durant', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(6, 218, 'Randy', 'Foye', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(34, 219, 'Josh', 'Huestis', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(9, 220, 'Serge', 'Ibaka', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(11, 221, 'Enes', 'Kanter', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(33, 222, 'Mitch', 'McGary', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(2, 223, 'Anthony', 'Morrow', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(22, 224, 'Cameron', 'Payne', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(21, 225, 'Andre', 'Roberson', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(5, 226, 'Kyle', 'Singler', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(3, 227, 'Dion', 'Waiters', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(0, 228, 'Russell', 'Westbrook', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(5, 229, 'Lavoy', 'Allen', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(10, 230, 'Chase', 'Budinger', 'Oklahoma City Thunder');
INSERT INTO Player VALUES(25, 231, 'Rakeem', 'Christmas', 'Indiana Pacers');
INSERT INTO Player VALUES(11, 232, 'Monta', 'Ellis', 'Indiana Pacers');
INSERT INTO Player VALUES(13, 233, 'Paul', 'George', 'Indiana Pacers');
INSERT INTO Player VALUES(3, 234, 'George', 'Hill', 'Indiana Pacers');
INSERT INTO Player VALUES(27, 235, 'Jordan', 'Hill', 'Indiana Pacers');
INSERT INTO Player VALUES(44, 236, 'Solomon', 'Hill', 'Indiana Pacers');
INSERT INTO Player VALUES(28, 237, 'Ian', 'Mahinmi', 'Indiana Pacers');
INSERT INTO Player VALUES(0, 238, 'C.J.', 'Miles', 'Indiana Pacers');
INSERT INTO Player VALUES(40, 239, 'Glenn', 'Robinson', 'Indiana Pacers');
INSERT INTO Player VALUES(2, 240, 'Rodney', 'Stuckey', 'Indiana Pacers');
INSERT INTO Player VALUES(33, 241, 'Myles', 'Turner', 'Indiana Pacers');
INSERT INTO Player VALUES(42, 242, 'Shayne', 'Whittington', 'Indiana Pacers');
INSERT INTO Player VALUES(1, 243, 'Joseph', 'Young', 'Indiana Pacers');
INSERT INTO Player VALUES(34, 244, 'Cliff', 'Alexander', 'Indiana Pacers');
INSERT INTO Player VALUES(8, 245, 'Al-Farouq', 'Aminu', 'Indiana Pacers');
INSERT INTO Player VALUES(5, 246, 'Pat', 'Connaughton', 'Portland Trail Blazers');
INSERT INTO Player VALUES(23, 247, 'Allen', 'Crabbe', 'Portland Trail Blazers');
INSERT INTO Player VALUES(17, 248, 'Ed', 'Davis', 'Portland Trail Blazers');
INSERT INTO Player VALUES(4, 249, 'Maurice', 'Harkless', 'Portland Trail Blazers');
INSERT INTO Player VALUES(9, 250, 'Gerald', 'Henderson', 'Portland Trail Blazers');
INSERT INTO Player VALUES(35, 251, 'Chris', 'Kaman', 'Portland Trail Blazers');
INSERT INTO Player VALUES(11, 252, 'Meyers', 'Leonard', 'Portland Trail Blazers');
INSERT INTO Player VALUES(0, 253, 'Damian', 'Lillard', 'Portland Trail Blazers');
INSERT INTO Player VALUES(3, 254, 'C.J.', 'McCollum', 'Portland Trail Blazers');
INSERT INTO Player VALUES(44, 255, 'Luis', 'Montero', 'Portland Trail Blazers');
INSERT INTO Player VALUES(24, 256, 'Mason', 'Plumlee', 'Portland Trail Blazers');
INSERT INTO Player VALUES(2, 257, 'Brian', 'Roberts', 'Portland Trail Blazers');
INSERT INTO Player VALUES(21, 258, 'Noah', 'Vonleh', 'Portland Trail Blazers');
INSERT INTO Player VALUES(34, 259, 'Giannis', 'Antetokounmpo', 'Portland Trail Blazers');
INSERT INTO Player VALUES(19, 260, 'Jerryd', 'Bayless', 'Portland Trail Blazers');
INSERT INTO Player VALUES(5, 261, 'Michael', 'Carter-Williams', 'Milwaukee Bucks');
INSERT INTO Player VALUES(11, 262, 'Tyler', 'Ennis', 'Milwaukee Bucks');
INSERT INTO Player VALUES(31, 263, 'John', 'Henson', 'Milwaukee Bucks');
INSERT INTO Player VALUES(17, 264, 'Damien', 'Inglis', 'Milwaukee Bucks');
INSERT INTO Player VALUES(3, 265, 'O.J.', 'Mayo', 'Milwaukee Bucks');
INSERT INTO Player VALUES(22, 266, 'Khris', 'Middleton', 'Milwaukee Bucks');
INSERT INTO Player VALUES(15, 267, 'Greg', 'Monroe', 'Milwaukee Bucks');
INSERT INTO Player VALUES(6, 268, 'Steve', 'Novak', 'Milwaukee Bucks');
INSERT INTO Player VALUES(77, 269, 'Johnny', 'OBryant', 'Milwaukee Bucks');
INSERT INTO Player VALUES(12, 270, 'Jabari', 'Parker', 'Milwaukee Bucks');
INSERT INTO Player VALUES(18, 271, 'Miles', 'Plumlee', 'Milwaukee Bucks');
INSERT INTO Player VALUES(21, 272, 'Greivis', 'Vasquez', 'Milwaukee Bucks');
INSERT INTO Player VALUES(20, 273, 'Rashad', 'Vaughn', 'Milwaukee Bucks');
INSERT INTO Player VALUES(33, 274, 'Trevor', 'Booker', 'Milwaukee Bucks');
INSERT INTO Player VALUES(3, 275, 'Trey', 'Burke', 'Milwaukee Bucks');
INSERT INTO Player VALUES(10, 276, 'Alec', 'Burks', 'Utah Jazz');
INSERT INTO Player VALUES(11, 277, 'Dante', 'Exum', 'Utah Jazz');
INSERT INTO Player VALUES(15, 278, 'Derrick', 'Favors', 'Utah Jazz');
INSERT INTO Player VALUES(27, 279, 'Rudy', 'Gobert', 'Utah Jazz');
INSERT INTO Player VALUES(20, 280, 'Gordon', 'Hayward', 'Utah Jazz');
INSERT INTO Player VALUES(5, 281, 'Rodney', 'Hood', 'Utah Jazz');
INSERT INTO Player VALUES(2, 282, 'Joe', 'Ingles', 'Utah Jazz');
INSERT INTO Player VALUES(23, 283, 'Chris', 'Johnson', 'Utah Jazz');
INSERT INTO Player VALUES(41, 284, 'Trey', 'Lyles', 'Utah Jazz');
INSERT INTO Player VALUES(8, 285, 'Shelvin', 'Mack', 'Utah Jazz');
INSERT INTO Player VALUES(25, 286, 'Raul', 'Neto', 'Utah Jazz');
INSERT INTO Player VALUES(21, 287, 'Tibor', 'PleiB', 'Utah Jazz');
INSERT INTO Player VALUES(24, 288, 'Jeff', 'Withey', 'Utah Jazz');
INSERT INTO Player VALUES(24, 289, 'Kent', 'Bazemore', 'Utah Jazz');
INSERT INTO Player VALUES(10, 290, 'Tim', 'Hardaway,', 'Utah Jazz');
INSERT INTO Player VALUES(12, 291, 'Kirk', 'Hinrich', 'Atlanta Hawks');
INSERT INTO Player VALUES(15, 292, 'Al', 'Horford', 'Atlanta Hawks');
INSERT INTO Player VALUES(26, 293, 'Kyle', 'Korver', 'Atlanta Hawks');
INSERT INTO Player VALUES(4, 294, 'Paul', 'Millsap', 'Atlanta Hawks');
INSERT INTO Player VALUES(31, 295, 'Mike', 'Muscala', 'Atlanta Hawks');
INSERT INTO Player VALUES(13, 296, 'Lamar', 'Patterson', 'Atlanta Hawks');
INSERT INTO Player VALUES(17, 297, 'Dennis', 'Schroder', 'Atlanta Hawks');
INSERT INTO Player VALUES(32, 298, 'Mike', 'Scott', 'Atlanta Hawks');
INSERT INTO Player VALUES(25, 299, 'Thabo', 'Sefolosha', 'Atlanta Hawks');
INSERT INTO Player VALUES(11, 300, 'Tiago', 'Splitter', 'Atlanta Hawks');
INSERT INTO Player VALUES(22, 301, 'Walter', 'Tavares', 'Atlanta Hawks');
INSERT INTO Player VALUES(0, 302, 'Jeff', 'Teague', 'Atlanta Hawks');
INSERT INTO Player VALUES(19, 303, 'Leandro', 'Barbosa', 'Atlanta Hawks');
INSERT INTO Player VALUES(40, 304, 'Harrison', 'Barnes', 'Atlanta Hawks');
INSERT INTO Player VALUES(12, 305, 'Andrew', 'Bogut', 'Golden State Warriors');
INSERT INTO Player VALUES(21, 306, 'Ian', 'Clark', 'Golden State Warriors');
INSERT INTO Player VALUES(30, 307, 'Stephen', 'Curry', 'Golden State Warriors');
INSERT INTO Player VALUES(31, 308, 'Festus', 'Ezeli', 'Golden State Warriors');
INSERT INTO Player VALUES(23, 309, 'Draymond', 'Green', 'Golden State Warriors');
INSERT INTO Player VALUES(9, 310, 'Andre', 'Iguodala', 'Golden State Warriors');
INSERT INTO Player VALUES(34, 311, 'Shaun', 'Livingston', 'Golden State Warriors');
INSERT INTO Player VALUES(36, 312, 'Kevon', 'Looney', 'Golden State Warriors');
INSERT INTO Player VALUES(20, 313, 'James', 'Michael', 'Golden State Warriors');
INSERT INTO Player VALUES(4, 314, 'Brandon', 'Rush', 'Golden State Warriors');
INSERT INTO Player VALUES(5, 315, 'Marreese', 'Speights', 'Golden State Warriors');
INSERT INTO Player VALUES(11, 316, 'Klay', 'Thompson', 'Golden State Warriors');
INSERT INTO Player VALUES(18, 317, 'Anderson', 'Varejao', 'Golden State Warriors');
INSERT INTO Player VALUES(5, 318, 'Nicolas', 'Batum', 'Golden State Warriors');
INSERT INTO Player VALUES(30, 319, 'Troy', 'Daniels', 'Golden State Warriors');
INSERT INTO Player VALUES(12, 320, 'Jorge', 'Gutierrez', 'Charlotte Hornets');
INSERT INTO Player VALUES(50, 321, 'Tyler', 'Hansbrough', 'Charlotte Hornets');
INSERT INTO Player VALUES(9, 322, 'Aaron', 'Harrison', 'Charlotte Hornets');
INSERT INTO Player VALUES(0, 323, 'Spencer', 'Hawes', 'Charlotte Hornets');
INSERT INTO Player VALUES(25, 324, 'Al', 'Jefferson', 'Charlotte Hornets');
INSERT INTO Player VALUES(44, 325, 'Frank', 'Kaminsky', 'Charlotte Hornets');
INSERT INTO Player VALUES(14, 326, 'Michael', 'Kidd-Gilchrist', 'Charlotte Hornets');
INSERT INTO Player VALUES(3, 327, 'Jeremy', 'Lamb', 'Charlotte Hornets');
INSERT INTO Player VALUES(1, 328, 'Courtney', 'Lee', 'Charlotte Hornets');
INSERT INTO Player VALUES(7, 329, 'Jeremy', 'Lin', 'Charlotte Hornets');
INSERT INTO Player VALUES(15, 330, 'Kemba', 'Walker', 'Charlotte Hornets');
INSERT INTO Player VALUES(2, 331, 'Marvin', 'Williams', 'Charlotte Hornets');
INSERT INTO Player VALUES(40, 332, 'Cody', 'Zeller', 'Charlotte Hornets');
INSERT INTO Player VALUES(45, 333, 'Cole', 'Aldrich', 'Charlotte Hornets');
INSERT INTO Player VALUES(11, 334, 'Jamal', 'Crawford', 'Charlotte Hornets');
INSERT INTO Player VALUES(22, 335, 'Branden', 'Dawson', 'Los Angeles Clippers');
INSERT INTO Player VALUES(8, 336, 'Jeff', 'Green', 'Los Angeles Clippers');
INSERT INTO Player VALUES(32, 337, 'Blake', 'Griffin', 'Los Angeles Clippers');
INSERT INTO Player VALUES(33, 338, 'Wesley', 'Johnson', 'Los Angeles Clippers');
INSERT INTO Player VALUES(6, 339, 'DeAndre', 'Jordan', 'Los Angeles Clippers');
INSERT INTO Player VALUES(12, 340, 'Luc', 'Mbah', 'Los Angeles Clippers');
INSERT INTO Player VALUES(3, 341, 'Chris', 'Paul', 'Los Angeles Clippers');
INSERT INTO Player VALUES(34, 342, 'Paul', 'Pierce', 'Los Angeles Clippers');
INSERT INTO Player VALUES(9, 343, 'Pablo', 'Prigioni', 'Los Angeles Clippers');
INSERT INTO Player VALUES(4, 344, 'J.J.', 'Redick', 'Los Angeles Clippers');
INSERT INTO Player VALUES(25, 345, 'Austin', 'Rivers', 'Los Angeles Clippers');
INSERT INTO Player VALUES(35, 346, 'Alex', 'Stepheson', 'Los Angeles Clippers');
INSERT INTO Player VALUES(30, 347, 'C.J.', 'Wilcox', 'Los Angeles Clippers');
INSERT INTO Player VALUES(1, 348, 'Chris', 'Bosh', 'Los Angeles Clippers');
INSERT INTO Player VALUES(9, 349, 'Luol', 'Deng', 'Los Angeles Clippers');
INSERT INTO Player VALUES(7, 350, 'Goran', 'Dragic', 'Miami Heat');
INSERT INTO Player VALUES(14, 351, 'Gerald', 'Green', 'Miami Heat');
INSERT INTO Player VALUES(40, 352, 'Udonis', 'Haslem', 'Miami Heat');
INSERT INTO Player VALUES(2, 353, 'Joe', 'Johnson', 'Miami Heat');
INSERT INTO Player VALUES(8, 354, 'Tyler', 'Johnson', 'Miami Heat');
INSERT INTO Player VALUES(4, 355, 'Josh', 'McRoberts', 'Miami Heat');
INSERT INTO Player VALUES(0, 356, 'Josh', 'Richardson', 'Miami Heat');
INSERT INTO Player VALUES(5, 357, 'Amare', 'Stoudemire', 'Miami Heat');
INSERT INTO Player VALUES(19, 358, 'Beno', 'Udrih', 'Miami Heat');
INSERT INTO Player VALUES(3, 359, 'Dwyane', 'Wade', 'Miami Heat');
INSERT INTO Player VALUES(21, 360, 'Hassan', 'Whiteside', 'Miami Heat');
INSERT INTO Player VALUES(20, 361, 'Justise', 'Winslow', 'Miami Heat');
INSERT INTO Player VALUES(2, 362, 'Brandon', 'Bass', 'Miami Heat');
INSERT INTO Player VALUES(28, 363, 'Tarik', 'Black', 'Miami Heat');
INSERT INTO Player VALUES(3, 364, 'Anthony', 'Brown', 'Los Angeles Lakers');
INSERT INTO Player VALUES(24, 365, 'Kobe', 'Bryant', 'Los Angeles Lakers');
INSERT INTO Player VALUES(6, 366, 'Jordan', 'Clarkson', 'Los Angeles Lakers');
INSERT INTO Player VALUES(17, 367, 'Roy', 'Hibbert', 'Los Angeles Lakers');
INSERT INTO Player VALUES(9, 368, 'Marcelo', 'Huertas', 'Los Angeles Lakers');
INSERT INTO Player VALUES(4, 369, 'Ryan', 'Kelly', 'Los Angeles Lakers');
INSERT INTO Player VALUES(7, 370, 'Larry', 'Nance', 'Los Angeles Lakers');
INSERT INTO Player VALUES(30, 371, 'Julius', 'Randle', 'Los Angeles Lakers');
INSERT INTO Player VALUES(1, 372, 'DAngelo', 'Russell', 'Los Angeles Lakers');
INSERT INTO Player VALUES(50, 373, 'Robert', 'Sacre', 'Los Angeles Lakers');
INSERT INTO Player VALUES(23, 374, 'Lou', 'Williams', 'Los Angeles Lakers');
INSERT INTO Player VALUES(37, 375, 'Metta', 'World', 'Los Angeles Lakers');
INSERT INTO Player VALUES(0, 376, 'Nick', 'Young', 'Los Angeles Lakers');
INSERT INTO Player VALUES(8, 377, 'Jared', 'Cunningham', 'Los Angeles Lakers');
INSERT INTO Player VALUES(3, 378, 'Dewayne', 'Dedmon', 'Los Angeles Lakers');
INSERT INTO Player VALUES(10, 379, 'Evan', 'Fournier', 'Orlando Magic');
INSERT INTO Player VALUES(0, 380, 'Aaron', 'Gordon', 'Orlando Magic');
INSERT INTO Player VALUES(23, 381, 'Mario', 'Hezonja', 'Orlando Magic');
INSERT INTO Player VALUES(7, 382, 'Ersan', 'Alyasova', 'Orlando Magic');
INSERT INTO Player VALUES(55, 383, 'Brandon', 'Jennings', 'Orlando Magic');
INSERT INTO Player VALUES(11, 384, 'Devyn', 'Marble', 'Orlando Magic');
INSERT INTO Player VALUES(13, 385, 'Shabazz', 'Napier', 'Orlando Magic');
INSERT INTO Player VALUES(44, 386, 'Andrew', 'Nicholson', 'Orlando Magic');
INSERT INTO Player VALUES(5, 387, 'Victor', 'Oladipo', 'Orlando Magic');
INSERT INTO Player VALUES(4, 388, 'Elfrid', 'Payton', 'Orlando Magic');
INSERT INTO Player VALUES(14, 389, 'Jason', 'Smith', 'Orlando Magic');
INSERT INTO Player VALUES(9, 390, 'Nikola', 'Vucevic', 'Orlando Magic');
INSERT INTO Player VALUES(32, 391, 'C.J.', 'Watson', 'Orlando Magic');
INSERT INTO Player VALUES(2, 392, 'Eric', 'Bledsoe', 'Orlando Magic');
INSERT INTO Player VALUES(1, 393, 'Devin', 'Booker', 'Orlando Magic');
INSERT INTO Player VALUES(4, 394, 'Tyson', 'Chandler', 'Phoenix Suns');
INSERT INTO Player VALUES(20, 395, 'Archie', 'Goodwin', 'Phoenix Suns');
INSERT INTO Player VALUES(43, 396, 'Kris', 'Humphries', 'Phoenix Suns');
INSERT INTO Player VALUES(23, 397, 'John', 'Jenkins', 'Phoenix Suns');
INSERT INTO Player VALUES(3, 398, 'Brandon', 'Knight', 'Phoenix Suns');
INSERT INTO Player VALUES(21, 399, 'Alex', 'Len', 'Phoenix Suns');
INSERT INTO Player VALUES(30, 400, 'Jon', 'Leuer', 'Phoenix Suns');
INSERT INTO Player VALUES(25, 401, 'Phil', 'Pressey', 'Phoenix Suns');
INSERT INTO Player VALUES(14, 402, 'Ronnie', 'Price', 'Phoenix Suns');
INSERT INTO Player VALUES(35, 403, 'Mirza', 'Teletovic', 'Phoenix Suns');
INSERT INTO Player VALUES(17, 404, 'P.J.', 'Tucker', 'Phoenix Suns');
INSERT INTO Player VALUES(12, 405, 'T.J.', 'Warren', 'Phoenix Suns');
INSERT INTO Player VALUES(10, 406, 'Sonny', 'Weems', 'Phoenix Suns');
INSERT INTO Player VALUES(6, 407, 'Alan', 'Anderson', 'Phoenix Suns');
INSERT INTO Player VALUES(3, 408, 'Bradley', 'Beal', 'Phoenix Suns');
INSERT INTO Player VALUES(1, 409, 'Jared', 'Dudley', 'Washington Wizards');
INSERT INTO Player VALUES(8, 410, 'Jarell', 'Eddie', 'Washington Wizards');
INSERT INTO Player VALUES(90, 411, 'Drew', 'Gooden', 'Washington Wizards');
INSERT INTO Player VALUES(13, 412, 'Marcin', 'Gortat', 'Washington Wizards');
INSERT INTO Player VALUES(21, 413, 'JJ', 'Hickson', 'Washington Wizards');
INSERT INTO Player VALUES(5, 414, 'Markieff', 'Morris', 'Washington Wizards');
INSERT INTO Player VALUES(14, 415, 'Gary', 'Neal', 'Washington Wizards');
INSERT INTO Player VALUES(42, 416, 'Nene', 'Hilario', 'Washington Wizards');
INSERT INTO Player VALUES(12, 417, 'Kelly', 'Oubre', 'Washington Wizards');
INSERT INTO Player VALUES(22, 418, 'Otto', 'Porter', 'Washington Wizards');
INSERT INTO Player VALUES(7, 419, 'Ramon', 'Sessions', 'Washington Wizards');
INSERT INTO Player VALUES(17, 420, 'Garrett', 'Temple', 'Washington Wizards');
INSERT INTO Player VALUES(2, 421, 'John', 'Wall', 'Washington Wizards');
INSERT INTO Player VALUES(13, 422, 'Quincy', 'Acy', 'Washington Wizards');
INSERT INTO Player VALUES(5, 423, 'James', 'Anderson', 'Washington Wizards');
INSERT INTO Player VALUES(3, 424, 'Marco', 'Belinelli', 'Sacramento Kings');
INSERT INTO Player VALUES(31, 425, 'Caron', 'Butler', 'Sacramento Kings');
INSERT INTO Player VALUES(18, 426, 'Omri', 'Casspi', 'Sacramento Kings');
INSERT INTO Player VALUES(0, 427, 'Willie', 'Cauley-Stein', 'Sacramento Kings');
INSERT INTO Player VALUES(7, 428, 'Darren', 'Collison', 'Sacramento Kings');
INSERT INTO Player VALUES(15, 429, 'DeMarcus', 'Cousins', 'Sacramento Kings');
INSERT INTO Player VALUES(30, 430, 'Seth', 'Curry', 'Sacramento Kings');
INSERT INTO Player VALUES(26, 431, 'Duje', 'Dukan', 'Sacramento Kings');
INSERT INTO Player VALUES(8, 432, 'Rudy', 'Gay', 'Sacramento Kings');
INSERT INTO Player VALUES(41, 433, 'Kosta', 'Koufos', 'Sacramento Kings');
INSERT INTO Player VALUES(23, 434, 'Ben', 'McLemore', 'Sacramento Kings');
INSERT INTO Player VALUES(25, 435, 'Eric', 'Moreland', 'Sacramento Kings');
INSERT INTO Player VALUES(9, 436, 'Rajon', 'Rondo', 'Sacramento Kings');