INSERT INTO Player VALUES(8, 0, 'Matthew Dellavedova 'Cleveland Cavaliers');
INSERT INTO Player VALUES(9, 1, 'Channing Frye 'Cleveland Cavaliers');
INSERT INTO Player VALUES(2, 2, 'Kyrie Irving 'Cleveland Cavaliers');
INSERT INTO Player VALUES(23, 3, 'LeBron James 'Cleveland Cavaliers');
INSERT INTO Player VALUES(24, 4, 'Richard Jefferson 'Cleveland Cavaliers');
INSERT INTO Player VALUES(1, 5, 'James Jones 'Cleveland Cavaliers');
INSERT INTO Player VALUES(14, 6, 'Sasha Kaun 'Cleveland Cavaliers');
INSERT INTO Player VALUES(0, 7, 'Kevin Love 'Cleveland Cavaliers');
INSERT INTO Player VALUES(20, 8, 'Timofey Mozgov 'Cleveland Cavaliers');
INSERT INTO Player VALUES(4, 9, 'Iman Shumpert 'Cleveland Cavaliers');
INSERT INTO Player VALUES(5, 10, 'J.R. Smith 'Cleveland Cavaliers');
INSERT INTO Player VALUES(13, 11, 'Tristan Thompson 'Cleveland Cavaliers');
INSERT INTO Player VALUES(52, 12, 'Mo Williams 'Cleveland Cavaliers');

INSERT INTO Player VALUES(15, 13, 'Anthony Bennett 'Toronto Raptors');
INSERT INTO Player VALUES(8, 14, 'Bismack Biyombo 'Toronto Raptors');
INSERT INTO Player VALUES(20, 15, 'Bruno Caboclo 'Toronto Raptors');
INSERT INTO Player VALUES(5, 16, 'DeMarre Carroll 'Toronto Raptors');
INSERT INTO Player VALUES(10, 17, 'DeMar DeRozan 'Toronto Raptors');
INSERT INTO Player VALUES(3, 18, 'James Johnson 'Toronto Raptors');
INSERT INTO Player VALUES(6, 19, 'Cory Joseph 'Toronto Raptors');
INSERT INTO Player VALUES(7, 20, 'Kyle Lowry 'Toronto Raptors');
INSERT INTO Player VALUES(92, 21, 'Lucas Nogueira 'Toronto Raptors');
INSERT INTO Player VALUES(54, 22, 'Patrick Patterson 'Toronto Raptors');
INSERT INTO Player VALUES(24, 23, 'Norman Powell 'Toronto Raptors');
INSERT INTO Player VALUES(31, 24, 'Terrence Ross 'Toronto Raptors');
INSERT INTO Player VALUES(4, 25, 'Luis Scola 'Toronto Raptors');
INSERT INTO Player VALUES(17, 26, 'Jonas Valanciunas 'Toronto Raptors');
INSERT INTO Player VALUES(55, 27, 'Delon Wright 'Toronto Raptors');

INSERT INTO Player VALUES(0, 28, 'Avery Bradley 'Boston Celtics');
INSERT INTO Player VALUES(99, 29, 'Jae Crowder 'Boston Celtics');
INSERT INTO Player VALUES(28, 30, 'R.J. Hunter 'Boston Celtics');
INSERT INTO Player VALUES(8, 31, 'Jonas Jerebko 'Boston Celtics');
INSERT INTO Player VALUES(90, 32, 'Amir Johnson 'Boston Celtics');
INSERT INTO Player VALUES(55, 33, 'Jordan Mickey 'Boston Celtics');
INSERT INTO Player VALUES(41, 34, 'Kelly Olynyk 'Boston Celtics');
INSERT INTO Player VALUES(12, 35, 'Terry Rozier 'Boston Celtics');
INSERT INTO Player VALUES(36, 36, 'Marcus Smart 'Boston Celtics');
INSERT INTO Player VALUES(7, 37, 'Jared Sullinger 'Boston Celtics');
INSERT INTO Player VALUES(4, 38, 'Isaiah Thomas 'Boston Celtics');
INSERT INTO Player VALUES(11, 39, 'Evan Turner 'Boston Celtics');
INSERT INTO Player VALUES(13, 40, 'James Young 'Boston Celtics');
INSERT INTO Player VALUES(44, 41, 'Tyler Zeller 'Boston Celtics');

INSERT INTO Player VALUES(1, 42, 'Chris Bosh 'Miami Heat');
INSERT INTO Player VALUES(9, 43, 'Luol Deng 'Miami Heat');
INSERT INTO Player VALUES(7, 44, 'Goran Dragic 'Miami Heat');
INSERT INTO Player VALUES(14, 45, 'Gerald Green 'Miami Heat');
INSERT INTO Player VALUES(40, 46, 'Udonis Haslem 'Miami Heat');
INSERT INTO Player VALUES(8, 47, 'Tyler Johnson 'Miami Heat');
INSERT INTO Player VALUES(4, 48, 'Josh McRoberts 'Miami Heat');
INSERT INTO Player VALUES(0, 49, 'Josh Richardson 'Miami Heat');
INSERT INTO Player VALUES(5, 50, 'Amare Stoudemire 'Miami Heat');
INSERT INTO Player VALUES(19, 51, 'Beno Udrih 'Miami Heat');
INSERT INTO Player VALUES(3, 52, 'Dwyane Wade 'Miami Heat');
INSERT INTO Player VALUES(21, 53, 'Hassan Whiteside 'Miami Heat');
INSERT INTO Player VALUES(20, 54, 'Justise Winslow 'Miami Heat');

INSERT INTO Player VALUES(24, 55, 'Kent Bazemore 'Atlanta Hawks');
INSERT INTO Player VALUES(10, 56, 'Tim Hardaway,Jr. 'Atlanta Hawks');
INSERT INTO Player VALUES(12, 57, 'Kirk Hinrich 'Atlanta Hawks');
INSERT INTO Player VALUES(15, 58, 'Al Horford 'Atlanta Hawks');
INSERT INTO Player VALUES(26, 59, 'Kyle Korver 'Atlanta Hawks');
INSERT INTO Player VALUES(4, 60, 'Paul Millsap 'Atlanta Hawks');
INSERT INTO Player VALUES(31, 61, 'Mike Muscala 'Atlanta Hawks');
INSERT INTO Player VALUES(13, 62, 'Lamar Patterson 'Atlanta Hawks');
INSERT INTO Player VALUES(17, 63, 'Dennis Schroder 'Atlanta Hawks');
INSERT INTO Player VALUES(32, 64, 'Mike Scott 'Atlanta Hawks');
INSERT INTO Player VALUES(25, 65, 'Thabo Sefolosha 'Atlanta Hawks');
INSERT INTO Player VALUES(11, 66, 'Tiago Splitter 'Atlanta Hawks');
INSERT INTO Player VALUES(22, 67, 'Walter Tavares 'Atlanta Hawks');
INSERT INTO Player VALUES(0, 68, 'Jeff Teague 'Atlanta Hawks');

INSERT INTO Player VALUES(5, 69, 'Lavoy Allen 'Indiana Pacers');
INSERT INTO Player VALUES(10, 70, 'Chase Budinger 'Indiana Pacers');
INSERT INTO Player VALUES(25, 71, 'Rakeem Christmas 'Indiana Pacers');
INSERT INTO Player VALUES(11, 72, 'Monta Ellis 'Indiana Pacers');
INSERT INTO Player VALUES(13, 73, 'Paul George 'Indiana Pacers');
INSERT INTO Player VALUES(3, 74, 'George Hill 'Indiana Pacers');
INSERT INTO Player VALUES(27, 75, 'Jordan Hill 'Indiana Pacers');
INSERT INTO Player VALUES(44, 76, 'Solomon Hill 'Indiana Pacers');
INSERT INTO Player VALUES(28, 77, 'Ian Mahinmi 'Indiana Pacers');
INSERT INTO Player VALUES(0, 78, 'C.J. Miles 'Indiana Pacers');
INSERT INTO Player VALUES(40, 79, 'Glenn Robinson III 'Indiana Pacers');
INSERT INTO Player VALUES(2, 80, 'Rodney Stuckey 'Indiana Pacers');
INSERT INTO Player VALUES(33, 81, 'Myles Turner 'Indiana Pacers');
INSERT INTO Player VALUES(42, 82, 'Shayne Whittington 'Indiana Pacers');
INSERT INTO Player VALUES(1, 83, 'Joseph Young 'Indiana Pacers');

INSERT INTO Player VALUES(5, 84, 'Nicolas Batum 'Charlotte Hornets');
INSERT INTO Player VALUES(30, 85, 'Troy Daniels 'Charlotte Hornets');
INSERT INTO Player VALUES(12, 86, 'Jorge Gutierrez 'Charlotte Hornets');
INSERT INTO Player VALUES(50, 87, 'Tyler Hansbrough 'Charlotte Hornets');
INSERT INTO Player VALUES(9, 88, 'Aaron Harrison 'Charlotte Hornets');
INSERT INTO Player VALUES(0, 89, 'Spencer Hawes 'Charlotte Hornets');
INSERT INTO Player VALUES(25, 90, 'Al Jefferson 'Charlotte Hornets');
INSERT INTO Player VALUES(44, 91, 'Frank Kaminsky 'Charlotte Hornets');
INSERT INTO Player VALUES(14, 92, 'Michael Kidd-Gilchrist 'Charlotte Hornets');
INSERT INTO Player VALUES(3, 93, 'Jeremy Lamb 'Charlotte Hornets');
INSERT INTO Player VALUES(1, 94, 'Courtney Lee 'Charlotte Hornets');
INSERT INTO Player VALUES(7, 95, 'Jeremy Lin 'Charlotte Hornets');
INSERT INTO Player VALUES(15, 96, 'Kemba Walker 'Charlotte Hornets');
INSERT INTO Player VALUES(2, 97, 'Marvin Williams 'Charlotte Hornets');
INSERT INTO Player VALUES(40, 98, 'Cody Zeller 'Charlotte Hornets');

INSERT INTO Player VALUES(41, 99, 'Cameron Bairstow 'Chicago Bulls');
INSERT INTO Player VALUES(0, 100, 'Aaron Brooks 'Chicago Bulls');
INSERT INTO Player VALUES(21, 101, 'Jimmy Butler 'Chicago Bulls');
INSERT INTO Player VALUES(34, 102, 'Mike Dunleavy 'Chicago Bulls');
INSERT INTO Player VALUES(6, 103, 'Cristiano Felicio 'Chicago Bulls');
INSERT INTO Player VALUES(16, 104, 'Pau Gasol 'Chicago Bulls');
INSERT INTO Player VALUES(22, 105, 'Taj Gibson 'Chicago Bulls');
INSERT INTO Player VALUES(7, 106, 'Justin Holiday 'Chicago Bulls');
INSERT INTO Player VALUES(3, 107, 'Doug McDermott 'Chicago Bulls');
INSERT INTO Player VALUES(44, 108, 'Nikola Mirotic 'Chicago Bulls');
INSERT INTO Player VALUES(55, 109, 'ETwaun Moore 'Chicago Bulls');
INSERT INTO Player VALUES(13, 110, 'Joakim Noah 'Chicago Bulls');
INSERT INTO Player VALUES(5, 111, 'Bobby Portis 'Chicago Bulls');
INSERT INTO Player VALUES(1, 112, 'Derrick Rose 'Chicago Bulls');
INSERT INTO Player VALUES(20, 113, 'Tony Snell 'Chicago Bulls');

INSERT INTO Player VALUES(50, 114, 'Joel Anthony 'Detroit Pistons');
INSERT INTO Player VALUES(12, 115, 'Aron Baynes 'Detroit Pistons');
INSERT INTO Player VALUES(22, 116, 'Steve Blake 'Detroit Pistons');
INSERT INTO Player VALUES(25, 117, 'Reggie Bullock 'Detroit Pistons');
INSERT INTO Player VALUES(5, 118, 'Kentavious Caldwell-Pope 'Detroit Pistons');
INSERT INTO Player VALUES(8, 119, 'Spencer Dinwiddie 'Detroit Pistons');
INSERT INTO Player VALUES(0, 120, 'Andre Drummond 'Detroit Pistons');
INSERT INTO Player VALUES(32, 121, 'Justin Harper 'Detroit Pistons');
INSERT INTO Player VALUES(34, 122, 'Tobias Harris 'Detroit Pistons');
INSERT INTO Player VALUES(6, 123, 'Darrun Hilliard 'Detroit Pistons');
INSERT INTO Player VALUES(1, 124, 'Reggie Jackson 'Detroit Pistons');
INSERT INTO Player VALUES(3, 125, 'Stanley Johnson 'Detroit Pistons');
INSERT INTO Player VALUES(20, 126, 'Jodie Meeks 'Detroit Pistons');
INSERT INTO Player VALUES(13, 127, 'Marcus Morris 'Detroit Pistons');
INSERT INTO Player VALUES(43, 128, 'Anthony Tolliver 'Detroit Pistons');

INSERT INTO Player VALUES(6, 129, 'Alan Anderson 'Washington Wizards');
INSERT INTO Player VALUES(3, 130, 'Bradley Beal 'Washington Wizards');
INSERT INTO Player VALUES(1, 131, 'Jared Dudley 'Washington Wizards');
INSERT INTO Player VALUES(8, 132, 'Jarell Eddie 'Washington Wizards');
INSERT INTO Player VALUES(90, 133, 'Drew Gooden 'Washington Wizards');
INSERT INTO Player VALUES(13, 134, 'Marcin Gortat 'Washington Wizards');
INSERT INTO Player VALUES(0, 135, 'JJ Hickson 'Washington Wizards');
INSERT INTO Player VALUES(5, 136, 'Markieff Morris 'Washington Wizards');
INSERT INTO Player VALUES(14, 137, 'Gary Neal 'Washington Wizards');
INSERT INTO Player VALUES(42, 138, 'Nene Hilario 'Washington Wizards');
INSERT INTO Player VALUES(12, 139, 'Kelly Oubre Jr 'Washington Wizards');
INSERT INTO Player VALUES(22, 140, 'Otto Porter 'Washington Wizards');
INSERT INTO Player VALUES(7, 141, 'Ramon Sessions 'Washington Wizards');
INSERT INTO Player VALUES(17, 142, 'Garrett Temple 'Washington Wizards');
INSERT INTO Player VALUES(2, 143, 'John Wall 'Washington Wizards');

INSERT INTO Player VALUES(3, 144, 'Dewayne Dedmon 'Orlando Magic');
INSERT INTO Player VALUES(10, 145, 'Evan Fournier 'Orlando Magic');
INSERT INTO Player VALUES(0, 146, 'Aaron Gordon 'Orlando Magic');
INSERT INTO Player VALUES(23, 147, 'Mario Hezonja 'Orlando Magic');
INSERT INTO Player VALUES(7, 148, 'Ersan Ä°lyasova 'Orlando Magic');
INSERT INTO Player VALUES(55, 149, 'Brandon Jennings 'Orlando Magic');
INSERT INTO Player VALUES(11, 150, 'Devyn Marble 'Orlando Magic');
INSERT INTO Player VALUES(13, 151, 'Shabazz Napier 'Orlando Magic');
INSERT INTO Player VALUES(44, 152, 'Andrew Nicholson 'Orlando Magic');
INSERT INTO Player VALUES(5, 153, 'Victor Oladipo 'Orlando Magic');
INSERT INTO Player VALUES(4, 154, 'Elfrid Payton 'Orlando Magic');
INSERT INTO Player VALUES(14, 155, 'Jason Smith 'Orlando Magic');
INSERT INTO Player VALUES(9, 156, 'Nikola Vucevic 'Orlando Magic');
INSERT INTO Player VALUES(32, 157, 'C.J. Watson 'Orlando Magic');

INSERT INTO Player VALUES(4, 158, 'Arron Afflalo 'New York Knicks');
INSERT INTO Player VALUES(17, 159, 'Lou Amundson 'New York Knicks');
INSERT INTO Player VALUES(7, 160, 'Carmelo Anthony 'New York Knicks');
INSERT INTO Player VALUES(3, 161, 'Jose Calderon 'New York Knicks');
INSERT INTO Player VALUES(11, 162, 'Cleanthony Early 'New York Knicks');
INSERT INTO Player VALUES(32, 163, 'Jimmer Fredette 'New York Knicks');
INSERT INTO Player VALUES(2, 164, 'Langston Galloway 'New York Knicks');
INSERT INTO Player VALUES(13, 165, 'Jerian Grant 'New York Knicks');
INSERT INTO Player VALUES(8, 166, 'Robin Lopez 'New York Knicks');
INSERT INTO Player VALUES(9, 167, 'Kyle OQuinn 'New York Knicks');
INSERT INTO Player VALUES(6, 168, 'Kristaps Porzingis 'New York Knicks');
INSERT INTO Player VALUES(1, 169, 'Kevin Seraphin 'New York Knicks');
INSERT INTO Player VALUES(42, 170, 'Lance Thomas 'New York Knicks');
INSERT INTO Player VALUES(18, 171, 'Sasha Vujacic 'New York Knicks');
INSERT INTO Player VALUES(23, 172, 'Derrick Williams 'New York Knicks');

INSERT INTO Player VALUES(34, 173, 'Giannis Antetokounmpo 'Milwaukee Bucks');
INSERT INTO Player VALUES(19, 174, 'Jerryd Bayless 'Milwaukee Bucks');
INSERT INTO Player VALUES(5, 175, 'Michael Carter-Williams 'Milwaukee Bucks');
INSERT INTO Player VALUES(11, 176, 'Tyler Ennis 'Milwaukee Bucks');
INSERT INTO Player VALUES(31, 177, 'John Henson 'Milwaukee Bucks');
INSERT INTO Player VALUES(17, 178, 'Damien Inglis 'Milwaukee Bucks');
INSERT INTO Player VALUES(3, 179, 'O.J. Mayo 'Milwaukee Bucks');
INSERT INTO Player VALUES(22, 180, 'Khris Middleton 'Milwaukee Bucks');
INSERT INTO Player VALUES(15, 181, 'Greg Monroe 'Milwaukee Bucks');
INSERT INTO Player VALUES(6, 182, 'Steve Novak 'Milwaukee Bucks');
INSERT INTO Player VALUES(77, 183, 'Johnny OBryantIII 'Milwaukee Bucks');
INSERT INTO Player VALUES(12, 184, 'Jabari Parker 'Milwaukee Bucks');
INSERT INTO Player VALUES(18, 185, 'Miles Plumlee 'Milwaukee Bucks');
INSERT INTO Player VALUES(21, 186, 'Greivis Vasquez 'Milwaukee Bucks');
INSERT INTO Player VALUES(20, 187, 'Rashad Vaughn 'Milwaukee Bucks');

INSERT INTO Player VALUES(44, 188, 'Bojan Bogdanovic 'Brooklyn Nets');
INSERT INTO Player VALUES(22, 189, 'Markel Brown 'Brooklyn Nets');
INSERT INTO Player VALUES(21, 190, 'Wayne Ellington 'Brooklyn Nets');
INSERT INTO Player VALUES(24, 191, 'Rondae Hollis-Jefferson 'Brooklyn Nets');
INSERT INTO Player VALUES(2, 192, 'Jarrett Jack 'Brooklyn Nets');
INSERT INTO Player VALUES(10, 193, 'Sergey Karasev 'Brooklyn Nets');
INSERT INTO Player VALUES(0, 194, 'Shane Larkin 'Brooklyn Nets');
INSERT INTO Player VALUES(11, 195, 'Brook Lopez 'Brooklyn Nets');
INSERT INTO Player VALUES(1, 196, 'Chris McCullough 'Brooklyn Nets');
INSERT INTO Player VALUES(33, 197, 'Willie Reed 'Brooklyn Nets');
INSERT INTO Player VALUES(41, 198, 'Thomas Robinson 'Brooklyn Nets');
INSERT INTO Player VALUES(15, 199, 'Donald Sloan 'Brooklyn Nets');
INSERT INTO Player VALUES(30, 200, 'Thaddeus Young 'Brooklyn Nets');

INSERT INTO Player VALUES(42, 201, 'Elton Brand 'Philadelphia 76ers');
INSERT INTO Player VALUES(0, 202, 'Isaiah Canaan 'Philadelphia 76ers');
INSERT INTO Player VALUES(33, 203, 'Robert Covington 'Philadelphia 76ers');
INSERT INTO Player VALUES(21, 204, 'Joel Embiid 'Philadelphia 76ers');
INSERT INTO Player VALUES(39, 205, 'Jerami Grant 'Philadelphia 76ers');
INSERT INTO Player VALUES(22, 206, 'Richaun Holmes 'Philadelphia 76ers');
INSERT INTO Player VALUES(7, 207, 'Carl Landry 'Philadelphia 76ers');
INSERT INTO Player VALUES(5, 208, 'Kendall Marshall 'Philadelphia 76ers');
INSERT INTO Player VALUES(12, 209, 'T.J. McConnell 'Philadelphia 76ers');
INSERT INTO Player VALUES(4, 210, 'Nerlens Noel 'Philadelphia 76ers');
INSERT INTO Player VALUES(8, 211, 'Jahlil Okafor 'Philadelphia 76ers');
INSERT INTO Player VALUES(1, 212, 'Ish Smith 'Philadelphia 76ers');
INSERT INTO Player VALUES(11, 213, 'Nik Stauskas 'Philadelphia 76ers');
INSERT INTO Player VALUES(31, 214, 'Hollis Thompson 'Philadelphia 76ers');

INSERT INTO Player VALUES(1, 250, 'Justin Anderson 'Dallas Mavericks');
INSERT INTO Player VALUES(5, 251, 'Jose Juan Barea 'Dallas Mavericks');
INSERT INTO Player VALUES(21, 252, 'Jeremy Evans 'Dallas Mavericks');
INSERT INTO Player VALUES(2, 253, 'Raymond Felton 'Dallas Mavericks');
INSERT INTO Player VALUES(34, 254, 'Devin Harris 'Dallas Mavericks');
INSERT INTO Player VALUES(42, 255, 'David Lee 'Dallas Mavericks');
INSERT INTO Player VALUES(23, 256, 'Wesley Matthews 'Dallas Mavericks');
INSERT INTO Player VALUES(11, 257, 'JaVale McGee 'Dallas Mavericks');
INSERT INTO Player VALUES(50, 258, 'Salah Mejri 'Dallas Mavericks');
INSERT INTO Player VALUES(41, 259, 'Dirk Nowitzki 'Dallas Mavericks');
INSERT INTO Player VALUES(27, 260, 'Zaza Pachulia 'Dallas Mavericks');
INSERT INTO Player VALUES(25, 261, 'Chandler Parsons 'Dallas Mavericks');
INSERT INTO Player VALUES(7, 262, 'Dwight Powell 'Dallas Mavericks');
INSERT INTO Player VALUES(3, 263, 'Charlie Villanueva 'Dallas Mavericks');
INSERT INTO Player VALUES(8, 264, 'Deron Williams 'Dallas Mavericks');

INSERT INTO Player VALUES(2, 265, 'Darrell Arthur 'Denver Nuggets');
INSERT INTO Player VALUES(12, 266, 'D.J. Augustin 'Denver Nuggets');
INSERT INTO Player VALUES(5, 267, 'Will Barton 'Denver Nuggets');
INSERT INTO Player VALUES(21, 268, 'Wilson Chandler 'Denver Nuggets');
INSERT INTO Player VALUES(35, 269, 'Kenneth Faried 'Denver Nuggets');
INSERT INTO Player VALUES(8, 270, 'Danilo Gallinari 'Denver Nuggets');
INSERT INTO Player VALUES(14, 271, 'Gary Harris 'Denver Nuggets');
INSERT INTO Player VALUES(15, 272, 'Nikola Jokic 'Denver Nuggets');
INSERT INTO Player VALUES(77, 273, 'Joffrey Lauvergne 'Denver Nuggets');
INSERT INTO Player VALUES(3, 274, 'Mike Miller 'Denver Nuggets');
INSERT INTO Player VALUES(0, 275, 'Emmanuel Mudiay 'Denver Nuggets');
INSERT INTO Player VALUES(1, 276, 'Jameer Nelson 'Denver Nuggets');
INSERT INTO Player VALUES(23, 277, 'Jusuf Nurkic 'Denver Nuggets');
INSERT INTO Player VALUES(9, 278, 'JaKarr Sampson 'Denver Nuggets');

INSERT INTO Player VALUES(19, 279, 'Leandro Barbosa 'Golden State Warriors');
INSERT INTO Player VALUES(40, 280, 'Harrison Barnes 'Golden State Warriors');
INSERT INTO Player VALUES(12, 281, 'Andrew Bogut 'Golden State Warriors');
INSERT INTO Player VALUES(21, 282, 'Ian Clark 'Golden State Warriors');
INSERT INTO Player VALUES(30, 283, 'Stephen Curry 'Golden State Warriors');
INSERT INTO Player VALUES(31, 284, 'Festus Ezeli 'Golden State Warriors');
INSERT INTO Player VALUES(23, 285, 'Draymond Green 'Golden State Warriors');
INSERT INTO Player VALUES(9, 286, 'Andre Iguodala 'Golden State Warriors');
INSERT INTO Player VALUES(34, 287, 'Shaun Livingston 'Golden State Warriors');
INSERT INTO Player VALUES(36, 288, 'Kevon Looney 'Golden State Warriors');
INSERT INTO Player VALUES(20, 289, 'James Michael 'Golden State Warriors');
INSERT INTO Player VALUES(4, 290, 'Brandon Rush 'Golden State Warriors');
INSERT INTO Player VALUES(5, 291, 'Marreese Speights 'Golden State Warriors');
INSERT INTO Player VALUES(11, 292, 'Klay Thompson 'Golden State Warriors');
INSERT INTO Player VALUES(18, 293, 'Anderson Varejao 'Golden State Warriors');

INSERT INTO Player VALUES(1, 294, 'Trevor Ariza 'Houston Rockets');
INSERT INTO Player VALUES(2, 295, 'Patrick Beverley 'Houston Rockets');
INSERT INTO Player VALUES(33, 296, 'Corey Brewer 'Houston Rockets');
INSERT INTO Player VALUES(15, 297, 'Clint Capela 'Houston Rockets');
INSERT INTO Player VALUES(7, 298, 'Sam Dekker 'Houston Rockets');
INSERT INTO Player VALUES(13, 299, 'James Harden 'Houston Rockets');
INSERT INTO Player VALUES(35, 300, 'Montrezl Harrell 'Houston Rockets');
INSERT INTO Player VALUES(12, 301, 'Dwight Howard 'Houston Rockets');
INSERT INTO Player VALUES(6, 302, 'Terrence Jones 'Houston Rockets');
INSERT INTO Player VALUES(3, 303, 'Ty Lawson 'Houston Rockets');
INSERT INTO Player VALUES(32, 304, 'K.J. McDaniels 'Houston Rockets');
INSERT INTO Player VALUES(20, 305, 'Donatas Motiejunas 'Houston Rockets');
INSERT INTO Player VALUES(5, 306, 'Josh Smith 'Houston Rockets');
INSERT INTO Player VALUES(31, 307, 'Jason Terry 'Houston Rockets');

INSERT INTO Player VALUES(45, 308, 'Cole Aldrich 'Los Angeles Clippers');
INSERT INTO Player VALUES(11, 309, 'Jamal Crawford 'Los Angeles Clippers');
INSERT INTO Player VALUES(22, 310, 'Branden Dawson 'Los Angeles Clippers');
INSERT INTO Player VALUES(8, 311, 'Jeff Green 'Los Angeles Clippers');
INSERT INTO Player VALUES(32, 312, 'Blake Griffin 'Los Angeles Clippers');
INSERT INTO Player VALUES(33, 313, 'Wesley Johnson 'Los Angeles Clippers');
INSERT INTO Player VALUES(6, 314, 'DeAndre Jordan 'Los Angeles Clippers');
INSERT INTO Player VALUES(12, 315, 'Luc Mbah 'Los Angeles Clippers');
INSERT INTO Player VALUES(3, 316, 'Chris Paul 'Los Angeles Clippers');
INSERT INTO Player VALUES(34, 317, 'Paul Pierce 'Los Angeles Clippers');
INSERT INTO Player VALUES(9, 318, 'Pablo Prigioni 'Los Angeles Clippers');
INSERT INTO Player VALUES(4, 319, 'J.J. Redick 'Los Angeles Clippers');
INSERT INTO Player VALUES(25, 320, 'Austin Rivers 'Los Angeles Clippers');
INSERT INTO Player VALUES(35, 321, 'Alex Stepheson 'Los Angeles Clippers');
INSERT INTO Player VALUES(30, 322, 'C.J. Wilcox 'Los Angeles Clippers');

INSERT INTO Player VALUES(2, 323, 'Brandon Bass 'Los Angeles Lakers');
INSERT INTO Player VALUES(28, 324, 'Tarik Black 'Los Angeles Lakers');
INSERT INTO Player VALUES(3, 325, 'Anthony Brown 'Los Angeles Lakers');
INSERT INTO Player VALUES(24, 326, 'Kobe Bryant 'Los Angeles Lakers');
INSERT INTO Player VALUES(6, 327, 'Jordan Clarkson 'Los Angeles Lakers');
INSERT INTO Player VALUES(17, 328, 'Roy Hibbert 'Los Angeles Lakers');
INSERT INTO Player VALUES(9, 329, 'Marcelo Huertas 'Los Angeles Lakers');
INSERT INTO Player VALUES(4, 330, 'Ryan Kelly 'Los Angeles Lakers');
INSERT INTO Player VALUES(7, 331, 'Larry Nance 'Los Angeles Lakers');
INSERT INTO Player VALUES(30, 332, 'Julius Randle 'Los Angeles Lakers');
INSERT INTO Player VALUES(1, 333, 'DAngelo Russell 'Los Angeles Lakers');
INSERT INTO Player VALUES(50, 334, 'Robert Sacre 'Los Angeles Lakers');
INSERT INTO Player VALUES(23, 335, 'Lou Williams 'Los Angeles Lakers');
INSERT INTO Player VALUES(37, 336, 'Metta World 'Los Angeles Lakers');
INSERT INTO Player VALUES(0, 337, 'Nick Young 'Los Angeles Lakers');

INSERT INTO Player VALUES(3, 338, 'Jordan Adams 'Memphis Grizzlies');
INSERT INTO Player VALUES(9, 339, 'Tony Allen 'Memphis Grizzlies');
INSERT INTO Player VALUES(7, 340, 'Chris Andersen 'Memphis Grizzlies');
INSERT INTO Player VALUES(22, 341, 'Matt Barnes 'Memphis Grizzlies');
INSERT INTO Player VALUES(15, 342, 'Vince Carter 'Memphis Grizzlies');
INSERT INTO Player VALUES(6, 343, 'Mario Chalmers 'Memphis Grizzlies');
INSERT INTO Player VALUES(11, 344, 'Mike Conley 'Memphis Grizzlies');
INSERT INTO Player VALUES(8, 345, 'James Ennis 'Memphis Grizzlies');
INSERT INTO Player VALUES(33, 346, 'Marc Gasol 'Memphis Grizzlies');
INSERT INTO Player VALUES(0, 347, 'JaMychal Green 'Memphis Grizzlies');
INSERT INTO Player VALUES(19, 348, 'P.J. Hairston 'Memphis Grizzlies');
INSERT INTO Player VALUES(10, 349, 'Jarell Martin 'Memphis Grizzlies');
INSERT INTO Player VALUES(50, 350, 'Zach Randolph 'Memphis Grizzlies');
INSERT INTO Player VALUES(1, 351, 'Lance Stephenson 'Memphis Grizzlies');
INSERT INTO Player VALUES(34, 352, 'Brandan Wright 'Memphis Grizzlies');

INSERT INTO Player VALUES(88, 353, 'Nemanja Bjelica 'Minnesota Timberwolves');
INSERT INTO Player VALUES(5, 354, 'Gorgui Dieng 'Minnesota Timberwolves');
INSERT INTO Player VALUES(21, 355, 'Kevin Garnett 'Minnesota Timberwolves');
INSERT INTO Player VALUES(1, 356, 'Tyus Jones 'Minnesota Timberwolves');
INSERT INTO Player VALUES(8, 357, 'Zach LaVine 'Minnesota Timberwolves');
INSERT INTO Player VALUES(23, 358, 'Kevin Martin 'Minnesota Timberwolves');
INSERT INTO Player VALUES(15, 359, 'Shabazz Muhammad 'Minnesota Timberwolves');
INSERT INTO Player VALUES(33, 360, 'Adreian Payne 'Minnesota Timberwolves');
INSERT INTO Player VALUES(14, 361, 'Nikola Pekovic 'Minnesota Timberwolves');
INSERT INTO Player VALUES(12, 362, 'Tayshaun Prince 'Minnesota Timberwolves');
INSERT INTO Player VALUES(9, 363, 'Ricky Rubio 'Minnesota Timberwolves');
INSERT INTO Player VALUES(10, 364, 'Damjan Rudez 'Minnesota Timberwolves');
INSERT INTO Player VALUES(32, 365, 'Karl-Anthony Towns 'Minnesota Timberwolves');
INSERT INTO Player VALUES(22, 366, 'Andrew Wiggins 'Minnesota Timberwolves');

INSERT INTO Player VALUES(42, 367, 'Alexis Ajinca 'New Orleans Pelicans');
INSERT INTO Player VALUES(33, 368, 'Ryan Anderson 'New Orleans Pelicans');
INSERT INTO Player VALUES(3, 369, 'Omer Asik 'New Orleans Pelicans');
INSERT INTO Player VALUES(8, 370, 'Luke Babbitt 'New Orleans Pelicans');
INSERT INTO Player VALUES(30, 371, 'Norris Cole 'New Orleans Pelicans');
INSERT INTO Player VALUES(44, 372, 'Dante Cunningham 'New Orleans Pelicans');
INSERT INTO Player VALUES(23, 373, 'Anthony Davis 'New Orleans Pelicans');
INSERT INTO Player VALUES(31, 374, 'Bryce Dejean-Jones 'New Orleans Pelicans');
INSERT INTO Player VALUES(16, 375, 'Toney Douglas 'New Orleans Pelicans');
INSERT INTO Player VALUES(1, 376, 'Tyreke Evans 'New Orleans Pelicans');
INSERT INTO Player VALUES(15, 377, 'Alonzo Gee 'New Orleans Pelicans');
INSERT INTO Player VALUES(10, 378, 'Eric Gordon 'New Orleans Pelicans');
INSERT INTO Player VALUES(11, 379, 'Jrue Holiday 'New Orleans Pelicans');
INSERT INTO Player VALUES(5, 380, 'Kendrick Perkins 'New Orleans Pelicans');
INSERT INTO Player VALUES(20, 381, 'Quincy Pondexter 'New Orleans Pelicans');

INSERT INTO Player VALUES(12, 382, 'Steven Adams 'Oklahoma City Thunder');
INSERT INTO Player VALUES(4, 383, 'Nick Collison 'Oklahoma City Thunder');
INSERT INTO Player VALUES(35, 384, 'Kevin Durant 'Oklahoma City Thunder');
INSERT INTO Player VALUES(6, 385, 'Randy Foye 'Oklahoma City Thunder');
INSERT INTO Player VALUES(34, 386, 'Josh Huestis 'Oklahoma City Thunder');
INSERT INTO Player VALUES(9, 387, 'Serge Ibaka 'Oklahoma City Thunder');
INSERT INTO Player VALUES(11, 388, 'Enes Kanter 'Oklahoma City Thunder');
INSERT INTO Player VALUES(33, 389, 'Mitch McGary 'Oklahoma City Thunder');
INSERT INTO Player VALUES(2, 390, 'Anthony Morrow 'Oklahoma City Thunder');
INSERT INTO Player VALUES(22, 391, 'Cameron Payne 'Oklahoma City Thunder');
INSERT INTO Player VALUES(21, 392, 'Andre Roberson 'Oklahoma City Thunder');
INSERT INTO Player VALUES(5, 393, 'Kyle Singler 'Oklahoma City Thunder');
INSERT INTO Player VALUES(3, 394, 'Dion Waiters 'Oklahoma City Thunder');
INSERT INTO Player VALUES(0, 395, 'Russell Westbrook 'Oklahoma City Thunder');

INSERT INTO Player VALUES(2, 396, 'Eric Bledsoe 'Phoenix Suns');
INSERT INTO Player VALUES(1, 397, 'Devin Booker 'Phoenix Suns');
INSERT INTO Player VALUES(4, 398, 'Tyson Chandler 'Phoenix Suns');
INSERT INTO Player VALUES(20, 399, 'Archie Goodwin 'Phoenix Suns');
INSERT INTO Player VALUES(43, 400, 'Kris Humphries 'Phoenix Suns');
INSERT INTO Player VALUES(23, 401, 'John Jenkins 'Phoenix Suns');
INSERT INTO Player VALUES(3, 402, 'Brandon Knight 'Phoenix Suns');
INSERT INTO Player VALUES(21, 403, 'Alex Len 'Phoenix Suns');
INSERT INTO Player VALUES(30, 404, 'Jon Leuer 'Phoenix Suns');
INSERT INTO Player VALUES(25, 405, 'Phil Pressey 'Phoenix Suns');
INSERT INTO Player VALUES(14, 406, 'Ronnie Price 'Phoenix Suns');
INSERT INTO Player VALUES(35, 407, 'Mirza Teletovic 'Phoenix Suns');
INSERT INTO Player VALUES(17, 408, 'P.J. Tucker 'Phoenix Suns');
INSERT INTO Player VALUES(12, 409, 'T.J. Warren 'Phoenix Suns');
INSERT INTO Player VALUES(10, 410, 'Sonny Weems 'Phoenix Suns');

INSERT INTO Player VALUES(34, 411, 'Cliff Alexander 'Portland Trail Blazers');
INSERT INTO Player VALUES(8, 412, 'Al-Farouq Aminu 'Portland Trail Blazers');
INSERT INTO Player VALUES(5, 413, 'Pat Connaughton 'Portland Trail Blazers');
INSERT INTO Player VALUES(23, 414, 'Allen Crabbe 'Portland Trail Blazers');
INSERT INTO Player VALUES(17, 415, 'Ed Davis 'Portland Trail Blazers');
INSERT INTO Player VALUES(4, 416, 'Maurice Harkless 'Portland Trail Blazers');
INSERT INTO Player VALUES(9, 417, 'Gerald Henderson 'Portland Trail Blazers');
INSERT INTO Player VALUES(35, 418, 'Chris Kaman 'Portland Trail Blazers');
INSERT INTO Player VALUES(11, 419, 'Meyers Leonard 'Portland Trail Blazers');
INSERT INTO Player VALUES(0, 420, 'Damian Lillard 'Portland Trail Blazers');
INSERT INTO Player VALUES(3, 421, 'C.J. McCollum 'Portland Trail Blazers');
INSERT INTO Player VALUES(44, 422, 'Luis Montero 'Portland Trail Blazers');
INSERT INTO Player VALUES(24, 423, 'Mason Plumlee 'Portland Trail Blazers');
INSERT INTO Player VALUES(2, 424, 'Brian Roberts 'Portland Trail Blazers');
INSERT INTO Player VALUES(21, 425, 'Noah Vonleh 'Portland Trail Blazers');

INSERT INTO Player VALUES(13, 426, 'Quincy Acy 'Sacramento Kings');
INSERT INTO Player VALUES(5, 427, 'James Anderson 'Sacramento Kings');
INSERT INTO Player VALUES(3, 428, 'Marco Belinelli 'Sacramento Kings');
INSERT INTO Player VALUES(31, 429, 'Caron Butler 'Sacramento Kings');
INSERT INTO Player VALUES(18, 430, 'Omri Casspi 'Sacramento Kings');
INSERT INTO Player VALUES(0, 431, 'Willie Cauley-Stein 'Sacramento Kings');
INSERT INTO Player VALUES(7, 432, 'Darren Collison 'Sacramento Kings');
INSERT INTO Player VALUES(15, 433, 'DeMarcus Cousins 'Sacramento Kings');
INSERT INTO Player VALUES(30, 434, 'Seth Curry 'Sacramento Kings');
INSERT INTO Player VALUES(26, 435, 'Duje Dukan 'Sacramento Kings');
INSERT INTO Player VALUES(8, 436, 'Rudy Gay 'Sacramento Kings');
INSERT INTO Player VALUES(41, 437, 'Kosta Koufos 'Sacramento Kings');
INSERT INTO Player VALUES(23, 438, 'Ben McLemore 'Sacramento Kings');
INSERT INTO Player VALUES(25, 439, 'Eric Moreland 'Sacramento Kings');
INSERT INTO Player VALUES(9, 440, 'Rajon Rondo 'Sacramento Kings');

INSERT INTO Player VALUES(12, 441, 'LaMarcus Aldridge 'San Antonio Spurs');
INSERT INTO Player VALUES(1, 442, 'Kyle Anderson 'San Antonio Spurs');
INSERT INTO Player VALUES(15, 443, 'Matt Bonner 'San Antonio Spurs');
INSERT INTO Player VALUES(18, 444, 'Rasual Butler 'San Antonio Spurs');
INSERT INTO Player VALUES(33, 445, 'Boris Diaw 'San Antonio Spurs');
INSERT INTO Player VALUES(21, 446, 'Tim Duncan 'San Antonio Spurs');
INSERT INTO Player VALUES(20, 447, 'Manu Ginobili 'San Antonio Spurs');
INSERT INTO Player VALUES(14, 448, 'Danny Green 'San Antonio Spurs');
INSERT INTO Player VALUES(2, 449, 'Kawhi Leonard 'San Antonio Spurs');
INSERT INTO Player VALUES(40, 450, 'Boban Marjanovic 'San Antonio Spurs');
INSERT INTO Player VALUES(3, 451, 'Ray McCallum 'San Antonio Spurs');
INSERT INTO Player VALUES(8, 452, 'Patty Mills 'San Antonio Spurs');
INSERT INTO Player VALUES(9, 453, 'Tony Parker 'San Antonio Spurs');
INSERT INTO Player VALUES(17, 454, 'Jonathon Simmons 'San Antonio Spurs');
INSERT INTO Player VALUES(30, 455, 'David West 'San Antonio Spurs');

INSERT INTO Player VALUES(33, 456, 'Trevor Booker 'Utah Jazz');
INSERT INTO Player VALUES(3, 457, 'Trey Burke 'Utah Jazz');
INSERT INTO Player VALUES(10, 458, 'Alec Burks 'Utah Jazz');
INSERT INTO Player VALUES(11, 459, 'Dante Exum 'Utah Jazz');
INSERT INTO Player VALUES(15, 460, 'Derrick Favors 'Utah Jazz');
INSERT INTO Player VALUES(27, 461, 'Rudy Gobert 'Utah Jazz');
INSERT INTO Player VALUES(20, 462, 'Gordon Hayward 'Utah Jazz');
INSERT INTO Player VALUES(5, 463, 'Rodney Hood 'Utah Jazz');
INSERT INTO Player VALUES(2, 464, 'Joe Ingles 'Utah Jazz');
INSERT INTO Player VALUES(23, 465, 'Chris Johnson 'Utah Jazz');
INSERT INTO Player VALUES(41, 466, 'Trey Lyles 'Utah Jazz');
INSERT INTO Player VALUES(8, 467, 'Shelvin Mack 'Utah Jazz');
INSERT INTO Player VALUES(25, 468, 'Raul Neto 'Utah Jazz');
INSERT INTO Player VALUES(21, 469, 'Tibor PleiB 'Utah Jazz');
INSERT INTO Player VALUES(24, 470, 'Jeff Withey 'Utah Jazz');