INSERT INTO CustomerProductRating VALUES(47, 40, '<rate customerID="47" productID="40"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(41, 5, '<rate customerID="41" productID="5"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(23, 18, '<rate customerID="23" productID="18"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(66, 8, '<rate customerID="66" productID="8"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(40, 7, '<rate customerID="40" productID="7"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(17, 42, '<rate customerID="17" productID="42"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(21, 1, '<rate customerID="21" productID="1"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(74, 45, '<rate customerID="74" productID="45"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(32, 42, '<rate customerID="32" productID="42"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(95, 48, '<rate customerID="95" productID="48"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(71, 20, '<rate customerID="71" productID="20"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(22, 40, '<rate customerID="22" productID="40"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(72, 30, '<rate customerID="72" productID="30"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(18, 15, '<rate customerID="18" productID="15"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(35, 33, '<rate customerID="35" productID="33"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(2, 35, '<rate customerID="2" productID="35"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(56, 13, '<rate customerID="56" productID="13"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(78, 23, '<rate customerID="78" productID="23"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(6, 16, '<rate customerID="6" productID="16"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(85, 36, '<rate customerID="85" productID="36"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(63, 5, '<rate customerID="63" productID="5"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(20, 1, '<rate customerID="20" productID="1"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(82, 18, '<rate customerID="82" productID="18"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(7, 31, '<rate customerID="7" productID="31"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(73, 33, '<rate customerID="73" productID="33"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(8, 14, '<rate customerID="8" productID="14"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(57, 23, '<rate customerID="57" productID="23"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(11, 9, '<rate customerID="11" productID="9"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(50, 25, '<rate customerID="50" productID="25"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(6, 20, '<rate customerID="6" productID="20"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(69, 29, '<rate customerID="69" productID="29"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(57, 43, '<rate customerID="57" productID="43"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(12, 46, '<rate customerID="12" productID="46"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(58, 20, '<rate customerID="58" productID="20"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(45, 35, '<rate customerID="45" productID="35"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(48, 2, '<rate customerID="48" productID="2"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(9, 43, '<rate customerID="9" productID="43"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(71, 47, '<rate customerID="71" productID="47"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(55, 15, '<rate customerID="55" productID="15"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(95, 26, '<rate customerID="95" productID="26"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(93, 4, '<rate customerID="93" productID="4"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(10, 40, '<rate customerID="10" productID="40"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(91, 15, '<rate customerID="91" productID="15"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(53, 38, '<rate customerID="53" productID="38"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(73, 41, '<rate customerID="73" productID="41"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(19, 18, '<rate customerID="19" productID="18"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(68, 6, '<rate customerID="68" productID="6"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(12, 5, '<rate customerID="12" productID="5"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(27, 31, '<rate customerID="27" productID="31"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(59, 44, '<rate customerID="59" productID="44"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(0, 47, '<rate customerID="0" productID="47"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(18, 36, '<rate customerID="18" productID="36"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(21, 44, '<rate customerID="21" productID="44"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(61, 22, '<rate customerID="61" productID="22"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(24, 24, '<rate customerID="24" productID="24"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(11, 33, '<rate customerID="11" productID="33"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(75, 17, '<rate customerID="75" productID="17"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(44, 44, '<rate customerID="44" productID="44"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(30, 10, '<rate customerID="30" productID="10"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(66, 12, '<rate customerID="66" productID="12"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(20, 27, '<rate customerID="20" productID="27"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(19, 9, '<rate customerID="19" productID="9"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(20, 3, '<rate customerID="20" productID="3"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(30, 6, '<rate customerID="30" productID="6"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(15, 25, '<rate customerID="15" productID="25"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(70, 37, '<rate customerID="70" productID="37"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(64, 5, '<rate customerID="64" productID="5"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(45, 38, '<rate customerID="45" productID="38"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(54, 48, '<rate customerID="54" productID="48"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(22, 17, '<rate customerID="22" productID="17"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(28, 47, '<rate customerID="28" productID="47"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(4, 25, '<rate customerID="4" productID="25"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(64, 30, '<rate customerID="64" productID="30"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(81, 16, '<rate customerID="81" productID="16"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(39, 41, '<rate customerID="39" productID="41"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(33, 50, '<rate customerID="33" productID="50"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(32, 1, '<rate customerID="32" productID="1"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(69, 48, '<rate customerID="69" productID="48"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(76, 43, '<rate customerID="76" productID="43"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(42, 39, '<rate customerID="42" productID="39"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(26, 36, '<rate customerID="26" productID="36"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(36, 10, '<rate customerID="36" productID="10"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(36, 44, '<rate customerID="36" productID="44"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(82, 22, '<rate customerID="82" productID="22"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(71, 16, '<rate customerID="71" productID="16"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(15, 49, '<rate customerID="15" productID="49"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(5, 35, '<rate customerID="5" productID="35"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(74, 9, '<rate customerID="74" productID="9"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(23, 17, '<rate customerID="23" productID="17"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(23, 21, '<rate customerID="23" productID="21"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(57, 26, '<rate customerID="57" productID="26"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(35, 45, '<rate customerID="35" productID="45"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(83, 37, '<rate customerID="83" productID="37"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(91, 34, '<rate customerID="91" productID="34"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(38, 45, '<rate customerID="38" productID="45"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(6, 6, '<rate customerID="6" productID="6"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(24, 8, '<rate customerID="24" productID="8"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(27, 37, '<rate customerID="27" productID="37"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(46, 49, '<rate customerID="46" productID="49"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(5, 38, '<rate customerID="5" productID="38"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(28, 14, '<rate customerID="28" productID="14"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(66, 34, '<rate customerID="66" productID="34"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(24, 19, '<rate customerID="24" productID="19"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(26, 26, '<rate customerID="26" productID="26"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(10, 11, '<rate customerID="10" productID="11"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(47, 31, '<rate customerID="47" productID="31"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(36, 38, '<rate customerID="36" productID="38"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(60, 46, '<rate customerID="60" productID="46"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(33, 26, '<rate customerID="33" productID="26"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(14, 41, '<rate customerID="14" productID="41"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(25, 11, '<rate customerID="25" productID="11"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(48, 8, '<rate customerID="48" productID="8"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(51, 23, '<rate customerID="51" productID="23"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(50, 27, '<rate customerID="50" productID="27"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(86, 13, '<rate customerID="86" productID="13"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(81, 19, '<rate customerID="81" productID="19"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(14, 33, '<rate customerID="14" productID="33"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(87, 4, '<rate customerID="87" productID="4"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(28, 13, '<rate customerID="28" productID="13"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(43, 7, '<rate customerID="43" productID="7"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(45, 22, '<rate customerID="45" productID="22"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(55, 13, '<rate customerID="55" productID="13"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(19, 12, '<rate customerID="19" productID="12"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(47, 29, '<rate customerID="47" productID="29"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(81, 29, '<rate customerID="81" productID="29"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(76, 28, '<rate customerID="76" productID="28"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(64, 26, '<rate customerID="64" productID="26"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(26, 37, '<rate customerID="26" productID="37"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(34, 32, '<rate customerID="34" productID="32"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(98, 43, '<rate customerID="98" productID="43"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(41, 20, '<rate customerID="41" productID="20"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(23, 12, '<rate customerID="23" productID="12"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(38, 41, '<rate customerID="38" productID="41"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(10, 19, '<rate customerID="10" productID="19"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(61, 11, '<rate customerID="61" productID="11"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(52, 34, '<rate customerID="52" productID="34"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(29, 10, '<rate customerID="29" productID="10"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(55, 9, '<rate customerID="55" productID="9"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(81, 35, '<rate customerID="81" productID="35"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(83, 18, '<rate customerID="83" productID="18"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(88, 24, '<rate customerID="88" productID="24"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(70, 16, '<rate customerID="70" productID="16"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(19, 45, '<rate customerID="19" productID="45"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(46, 19, '<rate customerID="46" productID="19"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(62, 13, '<rate customerID="62" productID="13"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(1, 12, '<rate customerID="1" productID="12"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(60, 25, '<rate customerID="60" productID="25"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(17, 49, '<rate customerID="17" productID="49"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(79, 5, '<rate customerID="79" productID="5"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(95, 13, '<rate customerID="95" productID="13"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(75, 48, '<rate customerID="75" productID="48"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(6, 28, '<rate customerID="6" productID="28"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(68, 12, '<rate customerID="68" productID="12"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(39, 2, '<rate customerID="39" productID="2"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(96, 22, '<rate customerID="96" productID="22"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(97, 6, '<rate customerID="97" productID="6"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(85, 15, '<rate customerID="85" productID="15"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(84, 49, '<rate customerID="84" productID="49"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(44, 1, '<rate customerID="44" productID="1"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(52, 2, '<rate customerID="52" productID="2"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(75, 41, '<rate customerID="75" productID="41"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(48, 32, '<rate customerID="48" productID="32"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(7, 22, '<rate customerID="7" productID="22"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(32, 32, '<rate customerID="32" productID="32"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(62, 18, '<rate customerID="62" productID="18"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(5, 42, '<rate customerID="5" productID="42"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(16, 27, '<rate customerID="16" productID="27"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(88, 2, '<rate customerID="88" productID="2"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(76, 19, '<rate customerID="76" productID="19"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(70, 4, '<rate customerID="70" productID="4"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(90, 4, '<rate customerID="90" productID="4"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(14, 19, '<rate customerID="14" productID="19"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(94, 45, '<rate customerID="94" productID="45"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(31, 14, '<rate customerID="31" productID="14"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(27, 3, '<rate customerID="27" productID="3"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(63, 29, '<rate customerID="63" productID="29"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(62, 43, '<rate customerID="62" productID="43"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(3, 22, '<rate customerID="3" productID="22"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(16, 12, '<rate customerID="16" productID="12"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(94, 50, '<rate customerID="94" productID="50"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(37, 47, '<rate customerID="37" productID="47"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(8, 17, '<rate customerID="8" productID="17"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(82, 49, '<rate customerID="82" productID="49"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(78, 21, '<rate customerID="78" productID="21"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(0, 31, '<rate customerID="0" productID="31"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(13, 34, '<rate customerID="13" productID="34"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(65, 47, '<rate customerID="65" productID="47"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(1, 5, '<rate customerID="1" productID="5"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(65, 5, '<rate customerID="65" productID="5"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(65, 9, '<rate customerID="65" productID="9"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(87, 10, '<rate customerID="87" productID="10"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(40, 6, '<rate customerID="40" productID="6"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(69, 44, '<rate customerID="69" productID="44"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(61, 4, '<rate customerID="61" productID="4"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(79, 43, '<rate customerID="79" productID="43"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(33, 33, '<rate customerID="33" productID="33"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(68, 44, '<rate customerID="68" productID="44"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(97, 28, '<rate customerID="97" productID="28"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(95, 10, '<rate customerID="95" productID="10"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(65, 1, '<rate customerID="65" productID="1"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(21, 42, '<rate customerID="21" productID="42"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(38, 46, '<rate customerID="38" productID="46"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(96, 15, '<rate customerID="96" productID="15"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(17, 37, '<rate customerID="17" productID="37"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(88, 31, '<rate customerID="88" productID="31"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(87, 27, '<rate customerID="87" productID="27"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(98, 2, '<rate customerID="98" productID="2"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(1, 4, '<rate customerID="1" productID="4"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(34, 29, '<rate customerID="34" productID="29"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(15, 4, '<rate customerID="15" productID="4"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(99, 46, '<rate customerID="99" productID="46"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(52, 28, '<rate customerID="52" productID="28"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(99, 11, '<rate customerID="99" productID="11"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(58, 30, '<rate customerID="58" productID="30"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(35, 47, '<rate customerID="35" productID="47"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(27, 39, '<rate customerID="27" productID="39"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(49, 43, '<rate customerID="49" productID="43"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(9, 31, '<rate customerID="9" productID="31"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(0, 28, '<rate customerID="0" productID="28"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(93, 7, '<rate customerID="93" productID="7"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(51, 7, '<rate customerID="51" productID="7"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(31, 28, '<rate customerID="31" productID="28"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(67, 3, '<rate customerID="67" productID="3"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(82, 20, '<rate customerID="82" productID="20"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(98, 32, '<rate customerID="98" productID="32"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(37, 35, '<rate customerID="37" productID="35"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(86, 24, '<rate customerID="86" productID="24"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(17, 23, '<rate customerID="17" productID="23"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(53, 36, '<rate customerID="53" productID="36"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(85, 2, '<rate customerID="85" productID="2"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(64, 37, '<rate customerID="64" productID="37"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(84, 45, '<rate customerID="84" productID="45"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(40, 13, '<rate customerID="40" productID="13"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(28, 17, '<rate customerID="28" productID="17"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(3, 26, '<rate customerID="3" productID="26"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(29, 39, '<rate customerID="29" productID="39"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(5, 30, '<rate customerID="5" productID="30"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(37, 18, '<rate customerID="37" productID="18"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(86, 40, '<rate customerID="86" productID="40"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(29, 33, '<rate customerID="29" productID="33"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(26, 6, '<rate customerID="26" productID="6"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(92, 38, '<rate customerID="92" productID="38"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(0, 24, '<rate customerID="0" productID="24"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(18, 37, '<rate customerID="18" productID="37"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(8, 18, '<rate customerID="8" productID="18"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(56, 3, '<rate customerID="56" productID="3"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(52, 25, '<rate customerID="52" productID="25"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(40, 36, '<rate customerID="40" productID="36"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(97, 4, '<rate customerID="97" productID="4"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(39, 25, '<rate customerID="39" productID="25"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(31, 16, '<rate customerID="31" productID="16"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(51, 41, '<rate customerID="51" productID="41"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(8, 46, '<rate customerID="8" productID="46"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(49, 25, '<rate customerID="49" productID="25"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(4, 39, '<rate customerID="4" productID="39"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(53, 21, '<rate customerID="53" productID="21"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(38, 39, '<rate customerID="38" productID="39"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(77, 9, '<rate customerID="77" productID="9"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(74, 24, '<rate customerID="74" productID="24"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(67, 48, '<rate customerID="67" productID="48"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(13, 7, '<rate customerID="13" productID="7"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(59, 28, '<rate customerID="59" productID="28"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(35, 21, '<rate customerID="35" productID="21"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(94, 7, '<rate customerID="94" productID="7"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(54, 24, '<rate customerID="54" productID="24"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(59, 27, '<rate customerID="59" productID="27"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(84, 3, '<rate customerID="84" productID="3"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(49, 21, '<rate customerID="49" productID="21"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(89, 30, '<rate customerID="89" productID="30"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(91, 25, '<rate customerID="91" productID="25"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(63, 30, '<rate customerID="63" productID="30"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(96, 32, '<rate customerID="96" productID="32"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(25, 24, '<rate customerID="25" productID="24"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(77, 11, '<rate customerID="77" productID="11"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(22, 20, '<rate customerID="22" productID="20"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(89, 48, '<rate customerID="89" productID="48"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(70, 40, '<rate customerID="70" productID="40"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(80, 21, '<rate customerID="80" productID="21"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(53, 16, '<rate customerID="53" productID="16"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(73, 17, '<rate customerID="73" productID="17"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(16, 34, '<rate customerID="16" productID="34"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(77, 1, '<rate customerID="77" productID="1"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(85, 14, '<rate customerID="85" productID="14"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(56, 32, '<rate customerID="56" productID="32"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(22, 23, '<rate customerID="22" productID="23"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(12, 13, '<rate customerID="12" productID="13"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(2, 3, '<rate customerID="2" productID="3"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(71, 43, '<rate customerID="71" productID="43"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(13, 2, '<rate customerID="13" productID="2"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(42, 45, '<rate customerID="42" productID="45"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(99, 1, '<rate customerID="99" productID="1"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(3, 40, '<rate customerID="3" productID="40"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(43, 2, '<rate customerID="43" productID="2"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(31, 8, '<rate customerID="31" productID="8"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(47, 26, '<rate customerID="47" productID="26"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(2, 41, '<rate customerID="2" productID="41"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(4, 30, '<rate customerID="4" productID="30"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(92, 14, '<rate customerID="92" productID="14"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(92, 40, '<rate customerID="92" productID="40"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(94, 38, '<rate customerID="94" productID="38"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(16, 36, '<rate customerID="16" productID="36"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(77, 10, '<rate customerID="77" productID="10"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(51, 45, '<rate customerID="51" productID="45"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(86, 20, '<rate customerID="86" productID="20"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(11, 48, '<rate customerID="11" productID="48"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(55, 8, '<rate customerID="55" productID="8"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(4, 3, '<rate customerID="4" productID="3"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(2, 38, '<rate customerID="2" productID="38"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(90, 39, '<rate customerID="90" productID="39"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(74, 8, '<rate customerID="74" productID="8"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(46, 9, '<rate customerID="46" productID="9"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(58, 42, '<rate customerID="58" productID="42"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(49, 42, '<rate customerID="49" productID="42"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(73, 47, '<rate customerID="73" productID="47"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(41, 23, '<rate customerID="41" productID="23"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(32, 46, '<rate customerID="32" productID="46"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(14, 11, '<rate customerID="14" productID="11"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(60, 44, '<rate customerID="60" productID="44"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(58, 19, '<rate customerID="58" productID="19"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(56, 12, '<rate customerID="56" productID="12"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(21, 36, '<rate customerID="21" productID="36"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(20, 36, '<rate customerID="20" productID="36"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(12, 37, '<rate customerID="12" productID="37"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(60, 22, '<rate customerID="60" productID="22"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(90, 15, '<rate customerID="90" productID="15"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(18, 42, '<rate customerID="18" productID="42"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(89, 50, '<rate customerID="89" productID="50"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(93, 14, '<rate customerID="93" productID="14"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(88, 40, '<rate customerID="88" productID="40"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(68, 33, '<rate customerID="68" productID="33"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(3, 15, '<rate customerID="3" productID="15"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(67, 24, '<rate customerID="67" productID="24"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(72, 11, '<rate customerID="72" productID="11"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(96, 50, '<rate customerID="96" productID="50"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(44, 31, '<rate customerID="44" productID="31"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(80, 6, '<rate customerID="80" productID="6"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(41, 46, '<rate customerID="41" productID="46"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(39, 17, '<rate customerID="39" productID="17"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(62, 19, '<rate customerID="62" productID="19"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(83, 21, '<rate customerID="83" productID="21"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(54, 35, '<rate customerID="54" productID="35"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(72, 7, '<rate customerID="72" productID="7"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(10, 8, '<rate customerID="10" productID="8"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(89, 33, '<rate customerID="89" productID="33"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(93, 12, '<rate customerID="93" productID="12"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(59, 34, '<rate customerID="59" productID="34"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(34, 49, '<rate customerID="34" productID="49"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(37, 20, '<rate customerID="37" productID="20"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(46, 8, '<rate customerID="46" productID="8"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(69, 16, '<rate customerID="69" productID="16"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(84, 29, '<rate customerID="84" productID="29"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(9, 50, '<rate customerID="9" productID="50"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(1, 32, '<rate customerID="1" productID="32"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(50, 6, '<rate customerID="50" productID="6"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(29, 21, '<rate customerID="29" productID="21"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(80, 50, '<rate customerID="80" productID="50"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(97, 30, '<rate customerID="97" productID="30"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(76, 27, '<rate customerID="76" productID="27"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(11, 39, '<rate customerID="11" productID="39"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(79, 26, '<rate customerID="79" productID="26"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(79, 41, '<rate customerID="79" productID="41"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(30, 18, '<rate customerID="30" productID="18"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(87, 29, '<rate customerID="87" productID="29"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(91, 29, '<rate customerID="91" productID="29"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(83, 28, '<rate customerID="83" productID="28"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(15, 15, '<rate customerID="15" productID="15"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(72, 46, '<rate customerID="72" productID="46"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(75, 5, '<rate customerID="75" productID="5"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(34, 17, '<rate customerID="34" productID="17"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(99, 23, '<rate customerID="99" productID="23"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(67, 10, '<rate customerID="67" productID="10"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(9, 49, '<rate customerID="9" productID="49"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(90, 1, '<rate customerID="90" productID="1"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(98, 14, '<rate customerID="98" productID="14"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(42, 32, '<rate customerID="42" productID="32"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(78, 14, '<rate customerID="78" productID="14"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(78, 42, '<rate customerID="78" productID="42"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(43, 3, '<rate customerID="43" productID="3"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(30, 34, '<rate customerID="30" productID="34"><star>4</star><description>THIS PRODUCT IS GOOD</description></rate>');
INSERT INTO CustomerProductRating VALUES(80, 16, '<rate customerID="80" productID="16"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(48, 35, '<rate customerID="48" productID="35"><star>3</star><description>THIS PRODUCT IS OKAY</description></rate>');
INSERT INTO CustomerProductRating VALUES(13, 9, '<rate customerID="13" productID="9"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(25, 27, '<rate customerID="25" productID="27"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(63, 47, '<rate customerID="63" productID="47"><star>2</star><description>THIS PRODUCT ALMOST SUCKS</description></rate>');
INSERT INTO CustomerProductRating VALUES(61, 50, '<rate customerID="61" productID="50"><star>5</star><description>THIS PRODUCT IS GREAT</description></rate>');
INSERT INTO CustomerProductRating VALUES(24, 49, '<rate customerID="24" productID="49"><star>1</star><description>THIS PRODUCT SUCKS</description></rate>');
