INSERT INTO TeamMerchandiseTeam VALUES(21, Boston Celtics);
INSERT INTO TeamMerchandiseTeam VALUES(22, Boston Celtics);
INSERT INTO TeamMerchandiseTeam VALUES(23, Dallas Mavericks);
INSERT INTO TeamMerchandiseTeam VALUES(24, Dallas Mavericks);
INSERT INTO TeamMerchandiseTeam VALUES(25, Brooklyn Nets);
INSERT INTO TeamMerchandiseTeam VALUES(26, Brooklyn Nets);
INSERT INTO TeamMerchandiseTeam VALUES(27, Houston Rockets);
INSERT INTO TeamMerchandiseTeam VALUES(28, Houston Rockets);
INSERT INTO TeamMerchandiseTeam VALUES(29, New York Knicks);
INSERT INTO TeamMerchandiseTeam VALUES(30, New York Knicks);
INSERT INTO TeamMerchandiseTeam VALUES(31, Memphis Grizzlies);
INSERT INTO TeamMerchandiseTeam VALUES(32, Memphis Grizzlies);
INSERT INTO TeamMerchandiseTeam VALUES(33, Philadelphia 76ers);
INSERT INTO TeamMerchandiseTeam VALUES(34, Philadelphia 76ers);
INSERT INTO TeamMerchandiseTeam VALUES(35, New Orleans Pelicans);
INSERT INTO TeamMerchandiseTeam VALUES(36, New Orleans Pelicans);
INSERT INTO TeamMerchandiseTeam VALUES(37, Toronto Raptors);
INSERT INTO TeamMerchandiseTeam VALUES(38, Toronto Raptors);
INSERT INTO TeamMerchandiseTeam VALUES(39, San Antonio Spurs);
INSERT INTO TeamMerchandiseTeam VALUES(40, San Antonio Spurs);
INSERT INTO TeamMerchandiseTeam VALUES(41, Chicago Bulls);
INSERT INTO TeamMerchandiseTeam VALUES(42, Chicago Bulls);
INSERT INTO TeamMerchandiseTeam VALUES(43, Denver Nuggets);
INSERT INTO TeamMerchandiseTeam VALUES(44, Denver Nuggets);
INSERT INTO TeamMerchandiseTeam VALUES(45, Cleveland Cavaliers);
INSERT INTO TeamMerchandiseTeam VALUES(46, Cleveland Cavaliers);
INSERT INTO TeamMerchandiseTeam VALUES(47, Minnesota Timberwolves);
INSERT INTO TeamMerchandiseTeam VALUES(48, Minnesota Timberwolves);
INSERT INTO TeamMerchandiseTeam VALUES(49, Detroit Pistons);
INSERT INTO TeamMerchandiseTeam VALUES(50, Detroit Pistons);
INSERT INTO TeamMerchandiseTeam VALUES(51, Oklahoma City Thunder);
INSERT INTO TeamMerchandiseTeam VALUES(52, Oklahoma City Thunder);
INSERT INTO TeamMerchandiseTeam VALUES(53, Indiana Pacers);
INSERT INTO TeamMerchandiseTeam VALUES(54, Indiana Pacers);
INSERT INTO TeamMerchandiseTeam VALUES(55, Portland Trail Blazers);
INSERT INTO TeamMerchandiseTeam VALUES(56, Portland Trail Blazers);
INSERT INTO TeamMerchandiseTeam VALUES(57, Milwaukee Bucks);
INSERT INTO TeamMerchandiseTeam VALUES(58, Milwaukee Bucks);
INSERT INTO TeamMerchandiseTeam VALUES(59, Utah Jazz);
INSERT INTO TeamMerchandiseTeam VALUES(60, Utah Jazz);
INSERT INTO TeamMerchandiseTeam VALUES(61, Atlanta Hawks);
INSERT INTO TeamMerchandiseTeam VALUES(62, Atlanta Hawks);
INSERT INTO TeamMerchandiseTeam VALUES(63, Golden State Warriors);
INSERT INTO TeamMerchandiseTeam VALUES(64, Golden State Warriors);
INSERT INTO TeamMerchandiseTeam VALUES(65, Charlotte Hornets);
INSERT INTO TeamMerchandiseTeam VALUES(66, Charlotte Hornets);
INSERT INTO TeamMerchandiseTeam VALUES(67, Los Angeles Clippers);
INSERT INTO TeamMerchandiseTeam VALUES(68, Los Angeles Clippers);
INSERT INTO TeamMerchandiseTeam VALUES(69, Miami Heat);
INSERT INTO TeamMerchandiseTeam VALUES(70, Miami Heat);
INSERT INTO TeamMerchandiseTeam VALUES(71, Los Angeles Lakers);
INSERT INTO TeamMerchandiseTeam VALUES(72, Los Angeles Lakers);
INSERT INTO TeamMerchandiseTeam VALUES(73, Orlando Magic);
INSERT INTO TeamMerchandiseTeam VALUES(74, Orlando Magic);
INSERT INTO TeamMerchandiseTeam VALUES(75, Phoenix Suns);
INSERT INTO TeamMerchandiseTeam VALUES(76, Phoenix Suns);
INSERT INTO TeamMerchandiseTeam VALUES(77, Washington Wizards);
INSERT INTO TeamMerchandiseTeam VALUES(78, Washington Wizards);
INSERT INTO TeamMerchandiseTeam VALUES(79, Sacramento Kings);
INSERT INTO TeamMerchandiseTeam VALUES(80, Sacramento Kings);
